### ISSUE TITLE
Opening of multiple instances of vlc

### ISSUE THREAD

**Issue by BlindEyeHalo** [bastimeyer/livestreamer-twitch-gui#103]
When starting a stream it always launches a new instance of VLC even if the "allow only one instance" option is checked, resulting in always ave to quit vlc when switching between streams.

**Comment by bastimeyer** [comment]
You actually want the single-instance mode to be enabled, or else you won't be able to watch multiple streams at the same time, since the same player window is used for all new streams. VLC also has a "single-instance from file manager" option. If you really want single-instance mode, you should enable both of these options, so it doesn't affect Livestreamer...

> have to quit vlc when switching between streams

See #86 or https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Player-configuration
