### ISSUE TITLE
Show minimized Livestreamer window when running executable again

### ISSUE THREAD

**Issue by RePlay-be** [bastimeyer/livestreamer-twitch-gui#105]
I have Livestreamer pinned to my taskbar for easy access and set it to minimize to tray. When Livestreamer is minimized to tray, you can't bring it up again when clicking on the taskbar icon or by double clicking on the executable: nothing happens. To show Livestreamer again you have to use the icon in the system tray.

I would prefer it if I could show the Livestreamer window by clicking on the taskbar icon as well. I assume this is tied to the functionality that stops you from launching multiple instances of the application?

When minimize to tray is disabled, it's also not possible to bring up Livestreamer again when double clicking the executable.

I had a quick look around in ApplicationController.js and LivestreamerController.js but I couldn't find it. Unfortunately I have no experience with NW.js so I'm not sure how to fix it myself...

**Comment by bastimeyer** [comment]
Unfortunately, this is beyond my control. As you've already guessed, this is tied to the [single-instance](https://github.com/nwjs/nw.js/wiki/Manifest-format#single-instance) mode of NW.js... To make this work you'd have to implement your own logic into the application instead of using the existing one. I don't think it's worth doing it. Maybe a feature request at the NW.js repo could be opened, asking for an event to be triggered or something like that when trying to open a second application instance.

**Comment by RePlay-be** [comment]
All right, thanks. I might open a feature request over at NW.js then. :)
