### ISSUE TITLE
Show online status when searching channels

### ISSUE THREAD

**Issue by omperus** [bastimeyer/livestreamer-twitch-gui#107]
It would be nice if the channels that come up when you do a search showed if the streamer is online or not, like a green dot next to the name or something, right now you have to enter to each channel details to see if they are online.

Another thing that i noticed is that channels hosting other broadcasters won't show up, is this being worked on?

Thanks for the amazing work, with the last update i can finally see streams without buffering problems :D

**Comment by bastimeyer** [comment]
> if the channels that come up when you do a search showed if the streamer is online or not

This can't be done without querying the API multiple times for each listed channel again, which would be incredibly inefficient. The streams are basically online streamers, so it's already implemented, just do a stream search instead of a channel search. [See the twitch API](https://github.com/justintv/Twitch-API/blob/master/v3_resources/search.md)...

> channels hosting other broadcasters

This doesn't work with livestreamer and is basically just a reference to another channel. The purpose of hosting another channel is that the viewers of the hoster can stay in the chat and discuss the hosted stream. As long as the chat isn't in the GUI yet, I don't feel the need of implementing this. The channel hosting function is also another thing that is not available on twitch's public API, so I don't know if this is going to change in the near future and would break stuff. So I'm not quite sure about this...

Thanks! :smile:
