### ISSUE TITLE
Error: Couldn't launch the stream

### ISSUE THREAD

**Issue by rtsintu** [bastimeyer/livestreamer-twitch-gui#111]
Some weird stuff is happening. GUI works ok. But there's this minor thing:
![image](https://cloud.githubusercontent.com/assets/12971736/8262366/6d50be36-16eb-11e5-9022-789117b29cbc.png)

Stream is launching and working alright though. When I click "Close" stream closes in the player.

Cant find where or why use "cvlc"

Win 8.1 x64, VLC 2.2.1 x64, livestreamer 1.12.2

**Comment by bastimeyer** [comment]
The reason why you are seeing this error message is VLC. Livestreamer is just passing through the VLC error message to stdErr (the GUI is then reacting to this), but it's still able to launch the stream because it's just a warning message of VLC. When clicking close, the GUI will terminate the livestreamer process which will also kill the video player.
This means that you need to fix your VLC in order to get through the launch dialog... Do you have any VLC plugins/skins installed which may be causing this issue?

**Comment by rtsintu** [comment]
No skins or plugins, just reinstalled it yesterday. Will try x32 version.

**Comment by bastimeyer** [comment]
Well, I can't help you here... Just try a different video player then.
