### ISSUE TITLE
Option to filter language

### ISSUE THREAD

**Issue by monkeyphysics** [bastimeyer/livestreamer-twitch-gui#113]
I'd like to configure in settings that I only want English casts, and have the gui hide all the Russian, Spanish, etc. streams, which are just noise to me in the overview.

**Comment by bastimeyer** [comment]
Well, sadly, there is no "nice" solution to this problem. The twitch API doesn't support language filters, so the only option would be removing items from a returned stream list. However, this would cause some issues... The infinite scroll mechanism is just one of those: Imagine the scenario where a user has only enabled one single language in which only a few poeple are streaming. Multiple consecutive API requests would be needed in order to fill the blank space of a stream list. This would increase the loading time by a lot. This is of course an example, but I hope you understand what I'm trying to say.

**Comment by monkeyphysics** [comment]
Simply reducing their opacity to 20% would already be a big win. Every other interface and backend function can remain untouched then?

**Comment by bastimeyer** [comment]
Yeah, this could work... Let me see...

**Comment by monkeyphysics** [comment]
Awesome, thanks!

**Comment by preovaleo** [comment]
Hello,

I reopen this because now there is a solution to filter by language : 
for example : 
http://api.twitch.tv/kraken/streams?limit=60&offset=0&broadcaster_language=en&on_site=1

perhaps the on_site things broke everything but ..

can you do something with that

good job
