### ISSUE TITLE
Auto Refresh?

### ISSUE THREAD

**Issue by joehanchoi** [bastimeyer/livestreamer-twitch-gui#114]
It's kinda annoying having to back out of a window and go back to refresh the stream list. Is it possible to auto-refresh whatever panel's active? Or is this a currently available setting I'm not currently aware of?

**Comment by bastimeyer** [comment]
> having to back out of a window and go back to refresh the stream list

There are multiple ways of refreshing a page:
- The refresh button at the top
- Clicking the same link that led to the page again (eg. inside the main menu)
- Pressing the reload hotkeys `F5` or `Ctrl-R`

> auto-refresh

I've already been asked before (#91) and I'm still not a fan of content that's being automatically replaced with something else. This can be unexpected and confusing. This could be implemented of course, in combination with an option in the settings menu, but shouldn't a manual refresh be enough?

There is some kind of auto refresh built in, though: If desktop notifications are enabled, the data of all followed channels/streams are being refreshed once every minute due to Ember's data bindings (thumbnails and image previews will not be reloaded)...

**Comment by fletom** [comment]
+1 for this feature

personally I have a second computer open with STG running on it all the time. I wish I could glance at it periodically and see my currently live streams, and open one if I want. currently I have to manually go the next screen and click the refresh button whenever I remember every few minutes or so.

I definitely agree that this, if implemented, should be off by default to prevent confusion about automatically replaced content. an ideal implementation would actually just activate the auto-refresh functionality when the app hasn't been interacted with in the last minute or two.

**Comment by bastimeyer** [comment]
@fletom 
See #226...
The requirement for an implementation of this feature was an upgrade of NW.js from the legacy versions to one of new releases (see the linked thread and the reference to the NW.js upgrade thread). This has been finally resolved in december, but I haven't had time yet for all the stuff like this feature request.

**Comment by fletom** [comment]
ah, good to know! glad it's being considered for the future.

thanks a million times for the great work you do on STG, I admire it greatly
