### ISSUE TITLE
Windows 10 Breaks Desktop Notifications

### ISSUE THREAD

**Issue by lmatthews94** [bastimeyer/livestreamer-twitch-gui#118]
Hello,

Can't be helped with the new update, however as it wasn't listed as an issue I thought I'd add it.

Basically, it allows you to click "Restart Desktop Notifications", which works, but straight after you have to do the same thing.
![1kcpcpu](https://cloud.githubusercontent.com/assets/1836176/8997224/c880a596-3716-11e5-8e93-e649ca6735cb.png)

**Comment by bastimeyer** [comment]
Hi!
I don't completely understand what you're trying to say, but the desktop notifications should be working perfectly fine (it does in all of my virtual machines, even in win10)...

The `Restart desktop notifications` button or link can only be seen if there was an issue with the polling of the followed streams/channels. Every minute, the GUI is asking the Twitch servers for the current list of followed channels and if there are any new ones, a new notification will be raised. Sometimes, the Twitch servers do not respond though (either because of your connection of because of a high server load, etc.), so the GUI will retry this request up to three times with a shorter delay of just one second. If all of those retries fail, no further requests will be made and a user action is required (the restart link), so it doesn't do that forever. The user-button in the titlebar will also have a different color, indicating that something went wrong.

So seeing this link just means, that you're having issues reaching the twitch servers or their system didn't return proper values (maybe because of a high server load, which happens from time to time).
