### ISSUE TITLE
Csgo drops

### ISSUE THREAD

**Issue by ignarteaga** [bastimeyer/livestreamer-twitch-gui#128]
Is it possible to receive a drop if im watching a stream that i open with the GUI?

I am logged in to my account and my account is linked to a steam account.

Thank you

**Comment by bastimeyer** [comment]
Well, I can't guarantee if this is working correctly, because I haven't received any items yet while watching dota2 or csgo (I've also never won any items while watching streams on their website) :sob:. But technically it should work as long as both steam accounts of you and the broadcaster are registered with twitch.

Whenever you're launching a stream via the GUI, it will tell Livestreamer to use the same [oauth access token](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.9.3/src/app/models/Livestreamer.js#L81) which you are logged in with. Livestreamer will then [validate this access token again](https://github.com/chrippa/livestreamer/blob/v1.12.2/src/livestreamer/plugins/twitch.py#L248) and will use it [while retrieving your viewer signature and playlist parameters](https://github.com/chrippa/livestreamer/blob/v1.12.2/src/livestreamer/plugins/twitch.py#L419). This signature *should be* linked to your account...

I've just seen that you've also opened this issue: chrippa/livestreamer#1039. Maybe someone can give you an answer over there...

**Comment by ignarteaga** [comment]
Thank you for answering dude.

Hope we get a drop this time :smile: 

Good luck.
