### ISSUE TITLE
Notification click no longer functions

### ISSUE THREAD

**Issue by SANstorming** [bastimeyer/livestreamer-twitch-gui#130]
(Windows) In the previous version of the app, clicking the desktop notification performed whatever action was set in the options, but in the latest release, I've noticed that it no longer seems to have any effect, regardless of what the option is set to.

**Comment by bastimeyer** [comment]
Which Windows version do you use? Nothing has changed in the latest release, so it should still be working correctly.

**Comment by SANstorming** [comment]
I'm using Windows 10. Hm, I wonder if anything has changed on my end then. Maybe I'll try redownloading the previous version and seeing if it works there.

**Comment by SANstorming** [comment]
Okay, tested on the previous version and it doesn't work there either. Not sure what happened, but it does seem to be a problem with my setup.

**Comment by bastimeyer** [comment]
Well, I don't know how I can help... The notification clicks are working fine on Windows 10.
But thanks to your thread, I've found an issue with notification icons on windows. Fixed it in 30e6696. It was trying to use the remote channel logo instead of the downloaded and cached file, which is required by the windows client...

**Comment by SANstorming** [comment]
Glad to hear something came out of it then! Thanks for the reply and I'll see if I can figure something out.
