### ISSUE TITLE
Gnome top bar application name

### ISSUE THREAD

**Issue by preovaleo** [bastimeyer/livestreamer-twitch-gui#134]
Hello,

A little improvement could be to set an application name on the gnome top bar

http://stackoverflow.com/questions/9324163/how-to-set-application-title-in-gnome-shell

![screenshot from 2015-09-06 19-20-16](https://cloud.githubusercontent.com/assets/6892913/9705676/d9950268-54cc-11e5-8341-426f15fc9fb0.png)

**Comment by preovaleo** [comment]
oups it seem to be an issue of nwjs
https://github.com/nwjs/nw.js/issues/3266

**Comment by bastimeyer** [comment]
Ok, thanks for letting me know. :smiley:

**Comment by hiisukun** [comment]
I have a current workaround for this. Unsure how helpful this is to other people, but having WM_CLASS set correctly also enabled most docks to work properly with livestreamer-twitch-gui. This includes Gnome extension dash-to-dock, cairo-dock, and plank. With the WM_CLASS set you can right click on dock icons and do "add as launcher/favourite", but without it you can't.

Instead of launching livestreamer with start.sh, I launch with the following startfixed.sh:

```
#!/bin/bash
/opt/livestreamer-twitch-gui/start.sh & setwmclass.sh $! Livestreamer-twitch-gui
```

In the above, the $! refers to the PID created when launching start.sh, and "Livestreamer-twitch-gui" is the WM_CLASS that appears to match best for use with dock programs.

The contents of setwmclass.sh is below. It takes two arguments: PID then WM_CLASS. It also has the requirement that you install wmctrl (should be in most modern distro repositories):
```
#!/bin/bash
# This utility sets the WM_CLASS of a window based upon a given PID.
# Requirements: wmctrl 

sleep 2

winid=$(wmctrl -lpx | grep $1 | cut -d' ' -f 1)
xprop -id ${winid} -f WM_CLASS 8s -set WM_CLASS $2
```

As you can see, it is fairly poor for error correction. Detecing no windows IDs found or waiting for the right window instead of using sleep isn't built in. Feel free to make improvements : D ... It uses wmctrl because xwininfo tended to list a lot of window IDs tied to processes that aren't actually visible windows.

Hope that helps in some way.

**Comment by bastimeyer** [comment]
Thank you very much @hiisukun!
Could you please integrate this into the `start.sh` script and open a pull request for me? I need to release a hotfix for `v0.10.0` pretty soon, and I'd like to include this workaround.

I had something like this in mind:

```bash
# run the application
exec -a "$0" "$HERE/$EXEC" "$@" &
pid=$!

# fix application name in gnome panel
if ( [[ "$XDG_CURRENT_DESKTOP" = "GNOME" ]] && [[ ! -z `which wmctrl` ]] ); then
	sleep 2
	winid=$(wmctrl -lpx | grep $pid | cut -d' ' -f 1)
	xprop -id ${winid} -f WM_CLASS 8s -set WM_CLASS "Livestreamer Twitch GUI"
fi

wait $pid
```

I'm not sure if the `$XDG_CURRENT_DESKTOP` and `which wmctrl` conditions are right/enough, though.

**Comment by hiisukun** [comment]
What do we do about wmctrl as a requirement? I had to apt-get/dnf it on my
installation.

**Comment by bastimeyer** [comment]
I have no idea how this can be fixed without `wmctrl`.
However, the script I've suggested is checking for wmctrl, so the workaround won't be executed unless it has been installed. If someone comes up with a better solution, this can easily be replaced again. Until then, I'm adding a note to the wiki.

**Comment by hiisukun** [comment]
Workin on it. 

I'll try and test on a few desktops, but it appears the situation between `$XDG_CURRENT_DESKTOP`, `$GDMSESSION` and `$DESKTOP_SESSION` is a little messy. Alternatively, it seems `wmctrl -m` for detecting the DE might be useful, since we're using it anyway.

I'll try and have something balanced between functional and thorough before tomorrow.

**Comment by bastimeyer** [comment]
thanks!
