### ISSUE TITLE
Stream Type RTMP & HLS switched around

### ISSUE THREAD

**Issue by Anonanon** [bastimeyer/livestreamer-twitch-gui#137]
When I select "rtmp" as Stream Type, I get customizable options for "HLS live edge" and "HLS segment threads", but they're not there anymore when I select "hls." Shouldn't this be the other way around?

![capture](https://cloud.githubusercontent.com/assets/1048428/9912516/05594dc2-5c76-11e5-80d9-905a8f280d57.PNG)

**Comment by bastimeyer** [comment]
I understand that this is a bit confusing, but it's intended.

By selecting `http` or `rtmp` as stream type, Livestreamer will transform the HLS stream from Twitch (Twitch uses HLS as streaming protocol) into the selected stream type, so both `--hls-live-edge` and `--hls-sedment-threads` properties are there for configuring the buffering behavior of Livestreamer. There are even some more parameters which are not included in the GUI settings, but those can be set in the `custom parameters` field or the livestreamer config file...
However, when you select `hls` as stream type, Livestreamer will just grab the Twitch HLS stream URL and forward it to your video player. Then the parameters are hidden, because your video player has to do all the buffering.

**Comment by Anonanon** [comment]
I see, thank you. Slightly unrelated, but I had extreme buffering issues with Livestreamer + VLC/MPC-HC, increasing network cache from 1000 to 2000/3000 did absolutely nothing but increase the startup times. I'm currently having really stable results with switching to rtmp and increasing HLS live edge to at least 6.

**Comment by bastimeyer** [comment]
In most cases, you can disable the video cache in your player to reduce the stream delay, if you have `http` or `rtmp` selected as stream type. Then just set the `--hls-live-edge` parameter to a value high enough, that it fits your connection to the Twitch servers. You may also want to change the [`--ringbuffer-size`](http://docs.livestreamer.io/cli.html#cmdoption--ringbuffer-size) value (needs to be set in the custom parameters field)...

If the buffering of livestreamer is good enough, disable player-side caching in `VLC` by adding the [`--network-caching=0`](https://wiki.videolan.org/VLC_command-line_help) player parameter, in `MPV` it's [`--no-cache`](http://mpv.io/manual/master/#options-no-cache). If you're using `MPC-HC` on Windows it's a bit more complicated and you need to [configure the buffering somewhere in in the LAV-Splitter settings](https://trac.mpc-hc.org/ticket/218).
