### ISSUE TITLE
Exit Code 1?

### ISSUE THREAD

**Issue by zack93rh** [bastimeyer/livestreamer-twitch-gui#138]
So I kept running into the "InsecurePlatform" error when I would launch streams using livestreamer and finally managed to fix that earlier today. However, now the twitch gui is broken and keeps saying "Error: Couldn't Launch the Stream" with "Exit Code 1" as the description. I imagine this has something to do with me reinstalling livestreamer, but I don't really know how to fix it. I've tried deleting the GUI application and the application support folder and reinstalling, but no dice. Has this come up before? Sorry if this is a common/stupid problem, but I'm still kind of a code noob.

**Comment by bastimeyer** [comment]
Are you sure you have fixed your livestreamer installation?
The error is being thrown at [this line](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.10.1/src/app/controllers/LivestreamerController.js#L278) and is caused by an error of the livestreamer process during the version validation.

Please run these commands from the shell and see if there are any errors (which most likely will be):
`livestreamer --version --no-version-check` (the validation command)
`livestreamer twitch.tv/CHANNEL best` (stream test command)

Btw, you don't need to remove/delete the GUI, as it will just execute these kind of commands and is not related to any of these livestreamer errors...

**Comment by zack93rh** [comment]
Validation command result: livestreamer 1.12.2 (that's all it spit out)
Stream test: works fine. 

The plugin is working fine currently, it seems.

**Comment by bastimeyer** [comment]
What's the exit code of the process?

On **\*nix** systems (and using a bash-like shell):
`livestreamer --version --no-version-check; echo $?`
On **Windows** systems:
`start /wait livestreamer --version --no-version-check & echo %ERRORLEVEL%`

> The plugin is working fine currently, it seems.

Are you talking about the twitch plugin of livestreamer?

**Comment by zack93rh** [comment]
http://imgur.com/a/FPraB

That's what I'm dealing with. The plugin itself will launch no problem, but the GUI won't open any streams and spits out that exit code.

**Comment by bastimeyer** [comment]
Yes, right, because livestreamer is exiting with status code 1 (code > 0 => error) during the validation. The output log is actually irrelevant...
Run `livestreamer --version --no-version-check &>/dev/null; echo $?` to see if it exits correctly.

The validation was broken in the v0.9.2 release (see #121), so maybe there is another yet undiscovered issue...

**Comment by zack93rh** [comment]
Oh, sweet! I'm still figuring out github. Hopefully one day I'll learn enough code to actually do something with it.

And yup, running that put out a 0. And I remember the validation breaking, but it seemed that was fixed once I reinstalled the plugin/made sure Python was updated.

**Comment by bastimeyer** [comment]
> And yup, running that put out a 0.

Are you sure you are running the same livestreamer executable as the GUI does? `which livestreamer` tells you the absolute path when you are just calling `livestreamer`.
On OSX, the application is unable to read from `$PATH`, so [multiple fallback paths](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.10.1/package.json#L44-L45) needed to be set. Please check in these paths for another livestreamer executable and see if it returns an error. If it does, go to the settings menu in the GUI and set the path to the one `which livestreamer` returned, so you are executing the working one when opening streams.

Other than that, I don't know what would cause this issue. It would mean, that the GUI would cause livestreamer to exit with an error, but executing it from the bash would not, and that doesn't make sense to me.

**Comment by zack93rh** [comment]
That fixed it! Thanks for all the help!

And I should note that the GUI didn't appear to be exiting the plugin itself, it simply wouldn't seem to load it. Like immediately upon clicking the stream, it would go to that error screen.

**Comment by bastimeyer** [comment]
yw
