### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by demethan** [bastimeyer/livestreamer-twitch-gui#140]
Hi, thanks for your app. 

I can`t stream because the proxy requires an authentication. Would it be possible to add proxy settings?

**Comment by bastimeyer** [comment]
You can use the custom livestreamer parameters in the GUI (requires advanced settings).
Just set the `--http-proxy "XYZ"` parameter if you are using a HTTP proxy. SOCKS proxies are currently not supported by livestreamer though (see chrippa/livestreamer#270).
I don't know if I want to add proxy config fields to the settings menu because of this...

There's also an open issue regarding proxy authentication:
chrippa/livestreamer#446

**Comment by demethan** [comment]
Ya, after some digging on google. I tried the parameters.  Unfortunately it didn't work. Even with Livestreamer. 

thanks for answering.

**Comment by icodeforlove** [comment]
You need to update your requests version, try this

`sudo pip install requests==2.5.3`
