### ISSUE TITLE
MVP : Failed to start player   ([Errno 13] Permission denied)

### ISSUE THREAD

**Issue by Caf** [bastimeyer/livestreamer-twitch-gui#141]
So I tried to start MVP instead of VLC. MVP is built via Homebrew. Works fine BUT...

1. If I try to link it in the GUI (selecting the simlink in /Application) I get a VERY weird and wrong path...
2. link the build directly :  /usr/local/Cellar/mpv/0.11.0/mpv.app  I get : error: Failed to start player: /usr/local/Cellar/mpv/0.11.0/mpv.app ([Errno 13] Permission denied)

I'm pretty sure I need to do something simple around the permissions but can't see what.  It's 5 AM too :P

**Comment by bastimeyer** [comment]
Yeah, I'm not sure how I can help you here...
From what it sounds like, it's not the fault of the GUI, since
`livestreamer --player "~/Applications/mpv.app" twitch.tv/CHANNEL best`
should be failing, too...

Maybe you should use the mpv executable inside the .app package (`mpv.app/Contents/MacOS/mpv`)...
You should also check whether you have the right permissions or not...
`stat -x ~/Applications/mpv.app/Contents/MacOS/mpv`

**Comment by Caf** [comment]
Thanks a lot, totally forgot about the inception of OS X, the App WITHIN the app. ;)  5Am = bad for the brain. SO, it's working with 
/usr/local/Cellar/mpv/0.11.0/mpv.app/Contents/MacOS/mpv
\o/
**BUT**, if I try those parameters : --title "{name} - {game} - {status}" (taken from here) in the settings, the video never starts. The player popup, but MPV is asking for a video so I guess the feed never reach it, at all. If I remove the "  I get a black player asking nothing but playing nothing.

**Comment by bastimeyer** [comment]
> if I try those parameters : --title "{name} - {game} - {status}" (taken from here) in the settings, the video never starts.

Add the [required `{filename}` parameter](https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Player-configuration#player-configurations) at the end to make it work...

**Comment by Caf** [comment]
Yep indeed. But some "complete" exemples would ease the process for everyone :P Thanks again for the awesome tool and the help!
