### ISSUE TITLE
Obtaining a login token

### ISSUE THREAD

**Issue by yunake** [bastimeyer/livestreamer-twitch-gui#144]
My Twitch account does not have a password since I use OpenID to sign in. This means I'm not able to sign in to livestreamer-twitch-gui since there's no option to use OpenID. I would gladly use the auth token, however I can't obtain one with correct permissions: the ones I already have for chatty & livestreamer don't work, and creating a new one for this gui requires knowing its client id.

Can you please provide an option to connect this app with twitch and use a token? Should be as simple as registering with Twitch and providing users with a api.twitch.tv/kraken/oauth2/authorize URL with correct aruments filled in.

**Comment by bastimeyer** [comment]
Yes, the application won't let you log in by using tokens created by different applications like Chatty or Livestreamer (with different clientids and scopes). The clientid is no secret though, you can easily find it [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.10.1/package.json#L57)... Make sure that [all required scopes](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.10.1/package.json#L59-L66) are set when generating the token and then you should be fine.
Also, don't forget to enable `adv. settings and features` at the top of the setting menu, so you can log in with your oauth token. Otherwise, the GUI will hide this option.

**Comment by yunake** [comment]
thanks, i managed to get a valid client token using this client id!

**Comment by bastimeyer** [comment]
:+1:
