### ISSUE TITLE
"Livestreamer could not be found"

### ISSUE THREAD

**Issue by an0thercat** [bastimeyer/livestreamer-twitch-gui#147]
Hi,
I installed Livestreamer Twitch GUI 0.10.1 on Mac OS 10.11.
When I tried to start a stream, I got the error message "Livestreamer could not be found".
In the GUI, I tried to select livestreamer (in the applications folder) as executable location and also selected mpv as videoplayer but it didn't do the trick.
Hope you can help. Sorry if it's a silly problem.

**Comment by bastimeyer** [comment]
Hi!
What's the location of the livestreamer executable on your system? Open the terminal and type `which livestreamer` to see and use this path in the GUI...
The GUI doesn't have access to environment variables (like `$PATH`) on OS X >= 10.10, so there are [a couple of fallback paths](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.10.1/package.json#L43-L46) which are being checked instead. I think it's just in a different folder on your system and I'd also like to know the path and how you've installed livestreamer.

The application folders (`/Applications` or `$HOME/Applications`) usually only contain "app bundles", and I'm surprised that there is a livestreamer "app"... Those app bundles are just special directory structures and the real executables can be found in the `Contents/MacOS` subfolder, so maybe you should check this, too.

**Comment by an0thercat** [comment]
You made me doubt when you asked how I've installed livestreamer and that there shouldn't be a livestreamer app. So I double-checked the wiki installation page and realised I didn't install livestreamer to begin with since I thought it was integrated with the GUI! I had the feeling this would be a noob issue.

So I installed livestreamer 1.12.2 by using the `sudo easy_install -U livestreamer` command line (I had a "[Errno 13] Permission denied" error without sudo) and it worked!
When I typed `which livestreamer` in the terminal, the path was `/usr/local/bin/livestreamer`

Just to be sure, to install future updates of livestreamer, you just have to dowload the latest package and install it the same way? Thank you very muche for your help!

**Comment by bastimeyer** [comment]
> Just to be sure, to install future updates of livestreamer, you just have to dowload the latest package and install it the same way?

If there are upgrades for `Livestreamer` you just have to execute the same command again and it will install the latest version. This will only be required if something Twitch related breaks (happened in december last year)...

If there are upgrades for the `Livestreamer Twitch GUI`, you will need to download the archive again. You'll receive a popup once a new version gets released. Right now, there are no packages for OSX (like for homebrew, etc.), but I'll see what I can do about this. Also, I don't know if putting the app into the AppStore is possible, because it might violate the TOS, and I'm also not a mac user, so I actually have no idea how this works.

> Thank you very much for your help!

You're welcome!
