### ISSUE TITLE
Phantom Window

### ISSUE THREAD

**Issue by craighton** [bastimeyer/livestreamer-twitch-gui#153]
My operating system is Windows 7 and I use the x64 version of the GUI tool. 

I've noticed sometimes when a stream has started and the GUI tool has minimized itself to the notification area the tooltips will sometimes show over my current application like I was still in the GUI tool. When I click it doesn't phantom activate the buttons but it will show random tooltips.

The only way I have found to rectify the problem is to open up the GUI tool and press the minimize button.

**Comment by bastimeyer** [comment]
So if I understand this correctly, you are able to trigger tooltips (like when hovering certain text nodes or block elements) inside the *hidden* application window? I'd like to see a screenshot of this, because I'm unable to reproduce this.
If this is reproducible, then I'd say, that this issue is related to NW.js and not to the application itself, because it's just [nwWindow.hide](https://github.com/nwjs/nw.js/wiki/Window#windowhide) that will be called when [toggling the window visibility](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.11.0/src/app/initializers/nwjs.js#L90)...

> When I click it doesn't phantom activate the buttons but it will show random tooltips

?

**Comment by craighton** [comment]
I'll try to grab a screenshot when I get home. 

To be clear, it pops up when the application minimizes itself and when my mouse happens to be where a tooltip would be if the window wasn't minimized.

**Comment by craighton** [comment]
Finally caught it, I had just started a Twitch stream and it had minimized itself. 

I was playing Counter-Strike: Global Offensive in windowed-mode. 

http://imgur.com/c5rwx3O

**Comment by bastimeyer** [comment]
Yeah as I said, this is related to either NW.js or Windows and can't be fixed. An idea would be to remove all the title attribute bindings from the HTMLElements while hiding the application window, but I don't know if this would even work.
Thanks for the effort though...
