### ISSUE TITLE
Delete config in package.json

### ISSUE THREAD

**Issue by preovaleo** [bastimeyer/livestreamer-twitch-gui#155]
If all the configuration are in metadata.json
can we clean the package.json file?

I see that the metadata file is in the gitignore file, why?

**Comment by bastimeyer** [comment]
The metadata.json is a combination of the config and dependencies objects of the `package.json` file, the dependencies object of the `bower.json` file and also a list of all `contributors` of the git repository with more than 3 commits. See [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.11.0/build/tasks/custom/metadata.js)...

So no, you cannot "clean" the package.json file, or else you won't be able to build the metadata.json file afterwards, which is require by the application to run. It's got its own entry in the .gitignore file, because it is stored in the `src` directory, so the application can be run from there as well (in addition to the `build/tmp` folder). Build instructions can be found [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.11.0/CONTRIBUTING.md#developing-and-building).
