### ISSUE TITLE
Am I counted as a viewer by Twitch?

### ISSUE THREAD

**Issue by Mathieu-C** [bastimeyer/livestreamer-twitch-gui#156]
Hi sorry no issue here but a question,

Am I actually detected as a logged viewer by Twitch when I use the GUI? I'm asking because some streams you can actually give you rewards, for example by watching the current CS:GO event with a Steam account linked to your Twitch one you have a chance to get a "souvenir" reward but for that you have to be a viewer on the official stream, is it the was with the GUI?

Thanks for your work.

**Comment by bastimeyer** [comment]
Hello!
I've already been asked this question a few weeks ago: https://github.com/bastimeyer/livestreamer-twitch-gui/issues/128#issuecomment-132077273

I'm afraid I still can't give a proper answer to that question. Twitch will track you as a viewer either by  processing the HLS-video-chunk requests linked with your OAuth token or by checking if you've joined the IRC channel of the broadcasting channel.

You better ask this question over at the livestreamer repo, since this actually doesn't belong here. There is an already open issue-thread linked in my linked comment...

**Comment by Mathieu-C** [comment]
Thanks for the quick reply, looks like I missed this thread while searching, my bad!
