### ISSUE TITLE
How to look at another video player?

### ISSUE THREAD

**Issue by ForumLiker** [bastimeyer/livestreamer-twitch-gui#158]
Hi. I want to open in the totem or bomi, but it says error. In vlc normally opens,but it is not my favorite player

**Comment by bastimeyer** [comment]
Hi!
Well, I don't know how I can help you. That's not a very detailed issue explanation...
Also, [please don't use the issue tracker for personal issues that are unrelated to the application](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/master/CONTRIBUTING.md#reporting-issues).

Did you try setting the right path to either of those players in the settings menu under the player section?
`which totem` or `which bomi` should return the path of those players.

Is it working without the GUI?
`livestreamer -p /path/to/player twitch.tv/CHANNEL best`

**Comment by ForumLiker** [comment]
Dont'w work 
http://storage8.static.itmages.ru/i/15/1031/h_1446301450_3311641_a8ea1f0be3.png

**Comment by bastimeyer** [comment]
This looks like you're having some codec issues, etc, and totem is unable to play the video stream. VLC has bundled all that stuff, that's why I think it's working for you...
Sorry, but I can't help you with your issue.. :worried:

I'm closing the thread now, since this has nothing to do with either **Livestreamer Twitch GUI** nor **Livestreamer**.
