### ISSUE TITLE
Autostart in tray

### ISSUE THREAD

**Issue by Mayurifag** [bastimeyer/livestreamer-twitch-gui#167]
How about autostart on launch setting? Want have an icon of this magnificent application after launch of my Windows and Archlinux. Thanks!

**Comment by bastimeyer** [comment]
> Autostart in tray

https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Launch-parameters

**Comment by Mayurifag** [comment]
I'm requesting all of it in settings in application, in gui.

**Comment by bastimeyer** [comment]
Well, IMO, this is totally unnecessary, since it would need to be implemented for Windows, OSX and various Linux desktop environments.
Just manually create a startup shortcut, which should only take about a couple of seconds, *once*...

**Comment by Lupinus** [comment]
Just found this issue with Google. Would it be possible to add a command line option (or maybe a setting) that will start the client minized/in tray? I like the notifications when someone goes live so I would like to have it sit in my system tray all the time.

I know how to add it to my autostart in Cinnamon but I've no clue how to start it in systray. I'm also not sure if that would even help all that much since the systray minimize features seems to be bound to the minized button, not the window state.

**Comment by bastimeyer** [comment]
> Would it be possible to add a command line option (or maybe a setting) that will start the client minized/in tray?

This already exists... See my comment above with the link to the wiki.

The `--tray` launch parameter works even if you've disabled tray mode in the settings.

**Comment by Lupinus** [comment]
Wow, I somehow missed that comment entirely. Thank you.
