### ISSUE TITLE
Forcibly adding Windows Start Menu shortcut

### ISSUE THREAD

**Issue by tmercswims** [bastimeyer/livestreamer-twitch-gui#173]
Problem observed on Windows 10, 64-bit, using the latest 64-bit release (0.11.1).

Whenever the program is opened, a shortcut is added to the Start Menu (specifically, it creates the file %AppData%\Microsoft\Windows\Start Menu\Programs\Livestreamer Twitch GUI.lnk). If the file is deleted, then it will be recreated upon next launch.

Personally, I like to keep my Start Menu organized, and moved the shortcut into a folder. But it is re-created every time the program is launched anyway, and it's irritating. I understand that it should be created upon first run, maybe, but after that it shouldn't be recreated every launch.

**Comment by bastimeyer** [comment]
See #44 why the [shortcut is being created](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.11.1/src/app/nwjs/shortcut.js#L35) at each start of the application.

The issue you're facing could be fixed by looking for already existing shortcuts in each subdirectory of the start menu folder, but I'm not sure if that could possibly cause other issues. Another solution could be adding a custom shortcut path that can be set in the settings menu for all Windows users...

Also, I don't know if you'd still be able to receive desktop notifications by changing the path of the shortcut. That's what the [desktop toast notifications page](https://msdn.microsoft.com/en-us/library/windows/desktop/hh802762(v=vs.85).aspx) says on MSDN:

> Without a valid shortcut installed in the Start screen or in All Programs, you cannot raise a toast notification from a desktop app.

**Comment by tmercswims** [comment]
Ah, I get you. Reading through #44, I suppose I will also just set it to hidden, as a workaround. Thanks for the quick reply, and the awesome program!
