### ISSUE TITLE
Long load timings

### ISSUE THREAD

**Issue by menghon** [bastimeyer/livestreamer-twitch-gui#174]
I have been encountering long load timings across different views (Streams, Games, etc) intermittently since quite a few releases ago.

Not too sure if this is an issue with the application or Twitch API calls restriction.

**Comment by bastimeyer** [comment]
The loading times depend on your connection to the twitch.tv API, the request size (number of items) and Ember.js' rendering engine.

So, if you're having a slow connection to the Twitch servers, loading times may be longer than usual. Personally, I haven't noticed any difference since months, at least here in germany. Does the Twitch.tv website also take a long time to load (ignoring its terrible/wasteful implementation of course)???

If you haven't already, you could try to minimize the request size by reducing the size of the application window, so less resources need to be loaded at a time...

In Ember.js (the framework that's being used), they've switched to a better rendering engine a couple of months ago (before the 1.13/2.0 upgrade). Overall, it's much faster, but it still has its flaws, like slightly longer initial loading times. I highly doubt, that there is any difference for this application, though. The startup time may be a bit longer on *slow* machines, but that's all.

Also, channel page details have been added in the last release (v0.11.1), which of course will increase the loading time by adding more items to the image preloader...

If you want to see the network requests of the GUI, you need to start the application with the `--remote-debugging-port=8888` parameter. Then open `http://localhost:8888` in your browser, click the `Livestreamer Twitch GUI` link and head over to the network tab. Now, whenever you're switching to a different menu, you should see all resources that are being loaded.

**Comment by menghon** [comment]
My window has 6 streams shown, with another 6 streams hidden before the application requests for more. Is this window size considered small?

For Twitch.tv website, I notice that profile pages take awhile to load but don't have any issues loading streams (source quality) or the Following page.

Some screenshots of the logs:
![logs](https://cloud.githubusercontent.com/assets/222205/11913118/37e7d390-a694-11e5-9e4d-2db3c36414c9.png)

![pending](https://cloud.githubusercontent.com/assets/222205/11913140/c41cc500-a694-11e5-87a8-d8630bed71dd.png)

**Comment by bastimeyer** [comment]
Well, the API response time of ~1 second (`api.twitch.tv`) seems to be fine in comparison to the **1 minute** :open_mouth: loading time of each of the images (`static-cdn.jtvnw.net`)... For me this looks like a network issue. Have you tried a traceroute yet?
`traceroute static-cdn.jtvnw.net` on Linux/OSX or `tracert static-cdn.jtvnw.net` on Windows.

Also, please delete the application's cache folder once, although I'm not sure if this can help. Go to the developer console (same place as the network graph) and enter `nwDispatcher.nwGui.App.dataPath` to get the path of the folder.

**Comment by menghon** [comment]
Traceroute looks normal at ~200ms. From the sequence of the network requests, the long load times are due to 1 or 2 requests that are taking extremely long.

Twitch site's Following page seems to be faster because the text and requested images are loaded first while the 1-2 image requests are still pending, as opposed to the application waiting for everything to be done.

**Comment by bastimeyer** [comment]
> application waiting for everything to be done

Yeah, this is how it's intended, so you're able to have fade-in animations with images that have finished loading.

Sadly, there's not much I can do for you at this point. I could give you a patch file that basically disables the image preloader, so you're not stuck in the loading animation. You'd need to compile the application on your own after applying the patch to the master branch then.

[disable-image-preloader.patch.zip](https://github.com/bastimeyer/livestreamer-twitch-gui/files/67494/disable-image-preloader.patch.zip)

**Comment by menghon** [comment]
I'll try that patch, thanks for your time!
