### ISSUE TITLE
Won't show anything when broadcaster is playing a playlist / hosting?

### ISSUE THREAD

**Issue by frumbert** [bastimeyer/livestreamer-twitch-gui#175]
I can watch a playlist (e.g. "channelname is broadcasting a Playlist", hosted stream "channel_name is hosting other_channel" through the web browser, but not through livestreamer? Is there a difference in the stream?

**Comment by bastimeyer** [comment]
You're in the wrong repo, this is **not** the [Livestreamer](https://github.com/chrippa/livestreamer) repository...

Let me answer your question anyway: If a channel is hosting another one, the one hosting is offline when querying the API. That's why you're unable to use the hoster's channel name while using livestreamer. Hosts need to be queried at a different API endpoint and livestreamer simply hasn't implemented this feature yet.

Hosts also haven't been implemented here yet (in the Livestreamer Twitch GUI), but I'm already thinking of adding this feature soon.

Are playlists already available on twitch? I thought they had announced this feature for mid 2016? Or are you talking about VODs?

**Comment by bastimeyer** [comment]
I'm closing this... If there are GUI-related host/playlist questions or feature requests, please open a proper issue thread.
