### ISSUE TITLE
Automatically refresh Livestreamer Twitch GUI

### ISSUE THREAD

**Issue by ThisIsIvan** [bastimeyer/livestreamer-twitch-gui#177]
Instead of having to hit the refresh button whenever you go back to the GUI after or while watching a stream, maybe the app could automatically and periodically refresh itself so you're always having the most recent list.

If possible refresh it whenever you have the window active/you activated the window.

**Comment by bastimeyer** [comment]
> maybe the app could automatically and periodically refresh itself

I've been asked to implement auto refresh mechanisms a couple of times in the past, but I still think that this would cause more confusion than it would benefit to the user. Auto refresh is just an absolute no-go for infinitescroll pages... Just press f5 / ctrl+r / cmd+r.
For normal pages this would not be as bad, due to the data-bindings of EmberJS. To be honest, channels that have been followed will already be periodically updated by the notification system. But this only updates the stream status/statistics and doesn't cause any issues with embedded images, etc.

> refresh it whenever you have the window active/you activated the window

IMO, this sounds like a much better idea. Should be behind a checkbox in the settings, though. And it should also only refresh if the window was out of focus or minimized for more than a minute or so.

**Comment by ThisIsIvan** [comment]
It's no so much about who's Streaming, but what is being streamed. 
I follow a lot of variety streamers, so I always check my followed list if a streamer is currently playing a game I enjoy watching. This goes hand in hand with my previous submission.

> IMO, this sounds like a much better idea. Should be behind a checkbox in the settings, though. And it should also only refresh if the window was out of focus or minimized for more than a minute or so.  

Agreed.

**Comment by Mayurifag** [comment]
I agree with topic starter, nice feature as well. I also need an auto-update list of streams after I click on livestreamer-gui from tray, because list of streamers who streamed since last update is kinda useless after some time.
