### ISSUE TITLE
Add support for all mouse buttons

### ISSUE THREAD

**Issue by ThisIsIvan** [bastimeyer/livestreamer-twitch-gui#180]
Clicking on mouse 2 - 5 currently does nothing. 
I think adding support for those buttons would enhance the user experience.

Some suggestions:
- Mouse4 and 5 should obviously make it possible to go back and forward.
- I could see being able to map something specific to mouse3. 
Like map "open chat" to mouse3, so when you click mouse3 on a stream (image) it would open up the stream's chat immediately. Or go to the channel settings, etc.
- Mouse2 could open up a context menu showing these (http://imgur.com/VsmiAvn) options for instance. Also you could enter the "channel settings" from there, which you can currently enter by clicking on the wrenge while viewing a channel.

**Comment by ThisIsIvan** [comment]
Just read that the API doesn't support other mouse events. 
I think this can be closed then, unless you can state something else?

**Comment by bastimeyer** [comment]
Thanks for the suggestions.

> Mouse4 and 5 should obviously make it possible to go back and forward.

See #85, nwjs/nw.js#3457...

> Like map "open chat" to mouse3, so when you click mouse3 on a stream (image) it would open up the stream's chat immediately.

Yeah, sounds reasonable. I think there should be a dropdown option for that in the settings menu though, so the user can decide what's going to happen.

> Mouse2 could open up a context menu showing these (http://imgur.com/VsmiAvn) options for instance.

I'd rather have real context menus which can be created by using the Menu API of NWjs. IIRC, I still have some stashed commits in my local repo from a couple of months ago with unfinished context menus. But I think I need to start fresh here, as I've changed a lot since then.

> I think this can be closed then

I'll keep this open for discussions about the mouse2+3 events...

**Comment by ThisIsIvan** [comment]
> > Mouse4 and 5 should obviously make it possible to go back and forward.
> See #85, nwjs/nw.js#3457...

An example from Opera could possibly provide a workaround (if implementable).
Holding mouse2 + clicking mouse1 -> go back.
Holding mouse1 + clicking mouse2 -> go forward.

It's suprisingly intuitive as well.

> I think there should be a dropdown option for that in the settings menu though, so the user can decide what's going to happen.

Sounds like a good solution.


Thank you for listening.

**Comment by bastimeyer** [comment]
Modifier + primary mouse button and middle mouse button options added in dff85e5...
Context menus still need to be added...
