### ISSUE TITLE
Add Audio Quality

### ISSUE THREAD

**Issue by 5paceToast** [bastimeyer/livestreamer-twitch-gui#195]
Potential uses:
- Not wanting to use too much bandwidth, but still participating in a stream.
- Having a stream open as background noise.
- Music streams (e.g Monstercat).

It seems like it'd be fairly simple to implement, upon first look just inserting `{ id: 4, label: "Audio Only",    quality: "audio" }` between lines 88 and 89 of `src/app/models/localstorage/Settings.js` should probably do it.

However I don't have a setup to test nodejs stuff (especially not UI ones) at the moment, so not making a PR that I can't test properly.

Since Livestreamer directly supports this use case, it should be fairly easy to implement regardless, more options = good, little to no downsides, and multiple potential use cases.

**Comment by bastimeyer** [comment]
Yes, sure, audio quality can of course be added. Thanks for the suggestion!

One issue could be the videoplayer config, though. When using mpv for instance, the `--force-window` parameter needs to be set, or otherwise you'll be only able to close the stream via the GUI. And this doesn't work if you've also selected the HLS passthrough option, since livestreamer ignores the player process in this case.

I should add this to the wiki...

**Comment by 5paceToast** [comment]
That's true, I'm using mpv but I set it up a while ago (and letting this use my config, which is nice)...
Probably adding a few mpv mentions into the wiki is the best route (another one is that when hls-streaming you need to use the audio display-sync variant, or *weird things* will happen (desync, stuttering, and other unpleasantness).
Anyway, I'll test it out upon next release, with any potential issues going into other issues (will reference this and commit).
