### ISSUE TITLE
Default Start Screen

### ISSUE THREAD

**Issue by torstenchr** [bastimeyer/livestreamer-twitch-gui#197]
Hi.

I would like to have a setting which allows me to choose which section the program starts. At the moment it always shows the features channels, but eg. I prefer to see my list of followed streamers.

There does not seem to be any where in settings to change this.

Regards,
Torsten.

**Comment by bastimeyer** [comment]
Hi,
this has already been implemented long time ago. See the button at the top-right corner with the three dots just below the close button. Hover or click it to open the quick settings menu and then click the button with the home icon to set the starting menu to the current one. There is no option for that in the settings menu, because it's easier and quicker to change it directly inside a menu.

**Comment by torstenchr** [comment]
My bad - I never notived those extra options on the differenc screen. But really cool feature and thanks for a great program!
