### ISSUE TITLE
any way to use native window scrolling on os x?

### ISSUE THREAD

**Issue by xaxxon** [bastimeyer/livestreamer-twitch-gui#204]
scrolling in the application is very jerky and difficult to control because it doesn't use native window scrolling - at least by default.

any way to change it to make it use native scrolling?

**Comment by bastimeyer** [comment]
No, you can't turn it off in the application, but there's a [compile-flag](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.11.2/package.json#L73) for turning the smooth-scroll library off.

I'm actually surprised to hear that it's jerky and difficult to control. Do you have changed any system related scrolling setting? I'm not an OSX user myself, so I don't know if there are any.
"Difficult to control" sounds like it's going too fast and this can only happen if more scroll events are being fired than normal. I've heard from a Windows user who had a similar issue and he had his mouse calibration messed up. Can this be the case here as well?

**Comment by xaxxon** [comment]
By difficult to control I mean that very small changes in how fast I move my fingers drastically change how fast the scrolling goes.   

Also, a very small movement, if the fingers are let off without stopping can really send the window scrolling very quickly.   

Simply pulling up livestreamer gui and another scrolling app that uses native scrolling and trying them side by side makes it pretty obvious how jumpy LTG is.

I'll go try the build flag, thank you for the answer, but it would be super great if this could be a setting.

**Comment by xaxxon** [comment]
I built it with that flag set to false.   The scrolling is wonderful, but the graphical performance is ass.   Is that the reason the smooth scrolling is turned on by default?

**Comment by xaxxon** [comment]
I made you a video: https://www.youtube.com/watch?v=hvgeY1AR5Us&feature=youtu.be

**Comment by bastimeyer** [comment]
> By difficult to control I mean that very small changes in how fast I move my fingers drastically change how fast the scrolling goes.

You must have changed some mousewheel/trackpad sensitivity settings (or you're not using the default ones), because like I've said earlier, it fires more scroll events than usual. Each [scroll event](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.11.2/src/app/gui/smoothscroll.js#L483) moves the screen by a fixed amount, depending on the [wheelDeltaY](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.11.2/src/app/gui/smoothscroll.js#L193-L194) value, which is expected to be [+-120](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.11.2/src/app/gui/smoothscroll.js#L20).

I'd like to know some values of the MouseWheel events from your machine, though. Could you please run `grunt metadata less:source run:src` from the path of the cloned repo? It'll launch the app from the source files and you're able to access the dev tools from here. In the dev tools, go to "Sources", expand the "Event listener breakpoints" on the right and then check the "mousewheel" event. Now when you scroll it'll stop and you can see the event in the "Scope Variables" section. Please tell me the values of `event.wheelDeltaY` and `event.detail`. These need to be `+-120` and `0` respectively. Thank you...

> the graphical performance is ass

I don't know what is happening here, haven't seen this before. This doesn't even happen in my VM, which doesn't have any GPU acceleration. This may be a NWjs issue, but I'm not sure...

**Comment by xaxxon** [comment]
I launched it from source with the smooth scroll set to false and clicked
mousewheel like you said but the app doesn't stop when I scroll.   The app
continues to run as normal.

http://i.imgur.com/r12cBwL.png

Ok, but after I turn smooth scrolling back on, I get the breakpoint.

event.wheeldeltay is -3 and event.detail is 0.

as far as the graphical performance, I'm on a current-model 13" retina mbp
on latest el capitan.

Also, I am running latest smoothmouse (because I hate the mouse
accelleration curve on os x), but it is disabled for trackpad and that's
what I'm using for the behavior I'm referring to.

**Comment by bastimeyer** [comment]
> event.wheeldeltay is -3 and event.detail is 0.

wheelDeltaY should be -120...

I had edited my post above. Github doesn't send out emails to thread subscribers when an edit is made, so maybe you have missed what I had added:

>Found this on a stackoverflow question:
>http://phrogz.net/js/wheeldelta.html
>This tries to normalize scroll events. Could you test this for me as well, please?

Please do this...

> I am running latest smoothmouse

Have you tried it without using it yet?

**Comment by bastimeyer** [comment]
Did you see the link I had posted a couple of days ago? Could you please check this for me real quick? Thanks

**Comment by michaelowens** [comment]
I'd like to see an option for this as well, purely because it's not like OS X native scrolling in the first place. It behaves more jumpy, seems a bit slower to start scrolling but then suddenly speeds up a fair amount faster. It's not as comfortable scrolling through the gui as it is scrolling through other apps.

**Comment by xaxxon** [comment]
At this point, i just run it out of the source command from earlier in this
thread with the smooth scrolling disabled.   It's not ideal, but whatever..

**Comment by xaxxon** [comment]
http://phrogz.net/js/wheeldelta.html

When I run that, no matter how slowly I move my mouse, I get +/-3 until I
hit a threshhold and it starts increasing.

If I flick scroll I can get it up to +/-500 for a split second.


Was that what you wanted?

**Comment by xaxxon** [comment]
all the numbers are: 3, 0, .025

and they stay there until I scroll fairly quickly - then they start going
up.  But from really slow to "a little on the slow side of normal
scrolling" is always 3.

**Comment by bastimeyer** [comment]
> When I run that, no matter how slowly I move my mouse, I get +/-3 until I hit a threshhold and it starts increasing.

This is unfixable then... There is no way of detecting dynamic scroll distance manipulations by 3rd party tools integrated into the OS.

I'll add a checkbox for disabling the smooth scroll library to the settings menu, so the user can do this during runtime.
#196

**Comment by xaxxon** [comment]
That sounds awesome!  Thank you.
