### ISSUE TITLE
Certain streamers show no video

### ISSUE THREAD

**Issue by scooby1222** [bastimeyer/livestreamer-twitch-gui#205]
Certain streams only have audio and no video, it is consistently from the same streamers and has been this way since I started using this about a month ago. This stream (http://www.twitch.tv/eloise_ailv) will never show any video in the player, I am using MPC.

**Comment by bastimeyer** [comment]
This doesn't sound like a "Livestreamer **Twitch GUI**" issue. It may be a **Livestreamer** related issue, but I doubt that as well. Livestreamer and Livestreamer Twitch GUI have nothing to with the video rendering of any player. Livestreamer may wrap the video/audio stream in a different transport protocol, but that's all.

Does the issue persist while using Livestreamer via the command line?
`livestreamer -p "/path/to/MPC.exe" twitch.tv/CHANNEL best`

Which stream type have you selected in the GUI's settings?

> it is consistently from the same streamers

Is it possible that these streamers are using different resolutions, framerates, bitrate or encoding quality/complexity settings, so that your player or system is having issues rendering these streams?

**Comment by bastimeyer** [comment]
Any response? This can be closed then, I guess?!

**Comment by scooby1222** [comment]
I haven't seen that streamer online, since. I will test it when I can

**Comment by scooby1222** [comment]
Tested again, the stream works when not in source quality so I guess it is an issue with MPC. Tested on VLC it works normally even on source quality
