### ISSUE TITLE
OSX player parameters are beeing ignored

### ISSUE THREAD

**Issue by Xelo** [bastimeyer/livestreamer-twitch-gui#208]
Hi,

just figured out that the Parameters for the video player are beeing ignored.

Quick workaround is adding the parameters after the player path directly.

like:
/Applications/VLC.app/Contents/MacOS/VLC --width=480 --height=270 --no-video-deco --video-on-top

Best,
Zerant

**Comment by bastimeyer** [comment]
The parameters will only be ignored if you don't specify a custom player path in the settings as well.
Also, please see the livestreamer documentation for the `--player` and `--player-args` parameters.

**Comment by Xelo** [comment]
Hi,

just testet it.
If I don't specify a `--player` then the `--player-args` are ignored and wont be used.
When I specify a `--player` then the `--player-args` are still not used.
When I do it like in the picture below then its working for me.
![screen shot 2016-02-02 at 15 52 48](https://cloud.githubusercontent.com/assets/5244468/12752944/0680ef54-c9c5-11e5-83bb-6b612899510d.png)

**Comment by bastimeyer** [comment]
Did you set the `{filename}` var?

When using custom player args (`--meta-title="foo" {filename}` for instance), the GUI will generate the following livestreamer parameter list, depending on all the other settings of course:
`--no-version-check --player "/Applications/VLC.app/Contents/MacOS/VLC" --player-args "--meta-title=\"foo\" {filename}" --player-passthrough http --hls-live-edge 3 --hls-segment-threads 1 twitch.tv/CHANNEL source,best`

You can see it for yourself, just run `ps -eo | grep $(which livestreamer) | head -n 1` while it's opening the stream (when you start seeing the livestreamer log output in the GUI). The command line may look a bit different, since quoted params are not being displayed correctly...

If livestreamer is not able to open your player, your custom player args are simply wrong. If there's an issue between the GUI and the generated command line, then it's worth of a bug report, but not if livestreamer parameters are being used incorrectly.

**Comment by Xelo** [comment]
No I didn't set the `{filename}` var.

The args that I use are :
`--width=480 --height=270 --no-video-deco --video-on-top`

When I am not setting `--player` then and add the args to `--player-args` I am getting following output from `ps -eo args | grep $(which livestreamer) | head -n 1`
`/usr/bin/python /usr/local/bin/livestreamer --no-version-check --player-passthrough http --player-continuous-http --twitch-oauth-token XXX --hls-live-edge 3 --hls-segment-threads 1 twitch.tv/CHANNEL source,best`

When I am setting `--player` to `/Applications/VLC.app/Contents/MacOS/VLC` and setting the `--player-args` to the one I posted on top I am getting:
`/usr/bin/python /usr/local/bin/livestreamer --no-version-check --player /Applications/VLC.app/Contents/MacOS/VLC --player-args  --width=480 --height=270 --no-video-deco --video-on-top --player-passthrough http --player-continuous-http --twitch-oauth-token XXX --hls-live-edge 3 --hls-segment-threads 1 twitch.tv/CHANNEL source,best`
But the player won't start.

When I am setting  `--player` to `/Applications/VLC.app/Contents/MacOS/VLC --width=480 --height=270 --no-video-deco --video-on-top` and leave the `--player-args` blank I am getting:
`/usr/bin/python /usr/local/bin/livestreamer --no-version-check --player /Applications/VLC.app/Contents/MacOS/VLC --width=480 --height=270 --no-video-deco --video-on-top --player-passthrough http --player-continuous-http --twitch-oauth-token mtxbr7xb7joshsel1p4q3n8947hu3e --hls-live-edge 3 --hls-segment-threads 1 twitch.tv/nightblue3 source,best`
But the player starts and I can watch the stream.

This is what confuses me.

Best,
Zerant

**Comment by bastimeyer** [comment]
> No I didn't set the {filename} var.

...

> Also, please see the livestreamer documentation for the --player and --player-args parameters.

http://docs.livestreamer.io/en/latest/cli.html#cmdoption--player-args

Once you are using `--player-args`, a `{filename}` var needs to be added.
