### ISSUE TITLE
Add Option to see always Streamtitle

### ISSUE THREAD

**Issue by Nexxxy** [bastimeyer/livestreamer-twitch-gui#215]
If i search for ADC only streamers in Games -> League of Legends .. I always have to go to the twitch online page, because i cant see streamtitles in Games -> Legaue of Legends Tab. 

(I know it is posible to toggle details .. but this would last too long if i click on every details button of all Streams that are currently online (2592 xD).

Therefore it would be awesome to exchange the Uptime + Viewerscount with the Streaming title.

Greetings
Nexxy

**Comment by bastimeyer** [comment]
I decided against adding titles, because they are too variable when you only have a limited amount of available space. The stream list items in the GUI are smaller than on the twitch website, because the GUI is a windowed application, whereas the twitch website will almost always be opened in a maximized browser window. That's why they can make use of all the available space.
Although they are using bigger list items, titles are still being cut off and most of them don't provide much info unless you are hovering it, so you can see the full title.
That's what you can do in the GUI as well without having to expand the info overlay. Just hover the preview image. From the overlay you can also directly open links from the stream title. You can't do this on the Twitch website...

Also, if you are searching for a specific title, then why don't you use the search function?

**Comment by ThisIsIvan** [comment]
> Why would you want to see a title that doesn't say much about the stream at all and waste space by doing this?  

I disagree with your opinion.  
Variety streamer post the for that day planned games in the title and match streams have the current opponents written in the title. So much is packed into the first characters that even the abbriviated version carries enough information. 
Most importantly streamer use the title to communicate with everyone who's not watching the stream, it's an important medium for the viewer and the streamer that it warrants its own place on the GUI.

Having to hover over the stream for the title is also really unintuitive.
When hovering over the stream it also takes too long for the title to show up. Maybe allow us to set the delay time?

Right below the stream name would be the perfect place for the title.

**Comment by Nexxxy** [comment]
+1 I couldn't have said it any better :D Fully agree with him.

**Comment by bastimeyer** [comment]
I've added a dropdown to the settings, so you can choose between showing the game or showing the title in the stream preview (default is the game being played). The expanded view will always show all informations, except while being in a game-menu, where the game info is redundant.

I really, really don't want to add another line of text below the preview image or somewhere else, because that would break the layout and I'd have to readjust the size of everything.
I think everyone can live with this solution. See the [`stream-title`](https://github.com/bastimeyer/livestreamer-twitch-gui/compare/master...stream-title) branch (not yet merged into master)...

**Comment by ThisIsIvan** [comment]
Understandable.

How about an option that allows us to set the delay between hovering over the stream preview and showing the title?
Checking on multiple streams atm is a pain since it takes so long for the title to pop up.

**Comment by bastimeyer** [comment]
I don't know what you are talking about. With the latest changes you're able to see the title without hovering anything. It's definitely not a pain...

Also, the animation when clicking the expand button at the bottom right of the preview image has a transition time of just 0.25s. I don't see anything wrong with it. I'm not going make it even more ridiculously complex the way it is right now with all the customizations.

I don't have any influence on the tooltip delay, if you're talking about that. That's determined by Chromium or your OS, can't tell...
