### ISSUE TITLE
Show hosts under followed streams

### ISSUE THREAD

**Issue by michaelowens** [bastimeyer/livestreamer-twitch-gui#220]
Just like the Twitch website. I often use this myself to find out where people I know are hanging out or finding new streams to watch that might be more what I'm looking for. Would love to be able to do this from the GUI.

It doesn't seem to be available on kraken API, so not sure if you're waiting for this, but currently it seems to be possible to get the info:
http://api.twitch.tv/api/users/{username}/followed/hosting

**Comment by bastimeyer** [comment]
I know, I have already started my work on hosted streams a couple of weeks ago, but I haven't finished it yet, because I'm still not sure how to properly implement this feature.

Hosted streams can't be merged with followed streams, because of the way the infinite scroll mechanism works, it's different on the Twitch website. This means that I need to add another route to the application, but I'm not sure if this is a good idea. The user would only click on this menu if he is bored or just browsing through different menus. On the Twitch website, hosted streams are directly integrated, so it's far more common for users to click on hosted streams. This makes me think if it's actually a good idea implementing this feature. I hope you know what I mean...

I also don't know if I want to add a link to this route to the main menu or if I should use a submenu, like Twitch does for their `/directory/following` route. VODs and other features may require links in the main menu in the future as well, so I'm not sure if this would unnecessarily bloat it up... I'm still deciding, although it should be fine using the main menu...

There's also an issue with the channel pages and asking the API whether the channel is hosting another one at the moment. This is done in a pretty stupid way by Twitch and whenever I see those "ad hoc" implementations by them, I can never be sure if they will remove this from their API in the future, breaking my implementation.
