### ISSUE TITLE
White line separating maximized app and taskbar on windows

### ISSUE THREAD

**Issue by adityakaulagi** [bastimeyer/livestreamer-twitch-gui#227]
Hi,

There is a small white line separating the bottom of the app and the taskbar when the app is maximized on windows. This is a minor issue, so no need to fix it urgently.  See image: https://imgur.com/WKS8ww2

Version: 0.12.0
OS: Windows 8.1

**Comment by bastimeyer** [comment]
This has nothing to do with the dark theme, it's a NW.js related issue and I can't do anything about it. It's a miscalculation of the content height of the application window in NW.js v0.12.3. This has been fixed in the latest release (v0.13.0), but I can't upgrade right now because of some other issues.
