### ISSUE TITLE
Text contrast is too low

### ISSUE THREAD

**Issue by CrendKing** [bastimeyer/livestreamer-twitch-gui#232]
### Description

I know everybody has different taste, but I found currently the app's text contrast is too low, and I can't read the text clearly. There was an issue https://github.com/bastimeyer/livestreamer-twitch-gui/issues/72 talking about flurry, but my problem is contrast.

From my perspective, the issue comes from two factors: font weight and color. To make sure it is not my monitor's problem, I checked the code. It looks like the main window uses `lighter` weight (https://github.com/bastimeyer/livestreamer-twitch-gui/search?q=font-weight&type=Code). Also, the font color looks like gray, not black.

I hope you can consider fixing this by either adjusting the font weight or color or both.Or, if you consider that too intrusive and backward incompatible, add an option to adjust them by user?

The same problem applies to the dark theme but slightly better. But when possible, I always prefer dark text on light background, which is less stressful to eyes (reference: http://uxmovement.com/content/when-to-use-white-text-on-a-dark-background/).

Thank you!
### Environment details (operating system, etc.)

Windows 10
### Comments, logs, screenshots, etc.

![clipboard01](https://cloud.githubusercontent.com/assets/975235/14224570/25846934-f856-11e5-9cc2-ae6f68637d70.jpg)

**Comment by bastimeyer** [comment]
> font weight

What you are talking about has nothing to do with the font-weight. Only the main menu and headlines have a `lighter` font-weight applied, but those are perfectly legible due to the increased font-size.

> color

See [the color definitions](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.13.0/src/styles/themes/default.less#L4-L9) of the default theme:

The background is `rgb(252, 252, 252)` and the default text is `rgba(0,0,0,.45)`, which results in `rgb(138,138,138)` on the default background. This is obviously not black and the contrast is not the greatest, but it should still be very well legible. I think your main complaint is the smaller text on the settings menu, which has `45% * (100% - 33%) = 30.15%` opacity.

I could increase the contrast a bit by setting the opacity of the default text color from `45%` to `55%` and by adjusting the other vars accordingly. I don't see any issues with the dark theme, though.

Compare your screenshot with mine (using Antergos (Linux) with slight font hinting and rgba antialiasing):

![screenshot from 2016-04-03 00-00-32](https://cloud.githubusercontent.com/assets/467294/14229343/992c2094-f931-11e5-8d2a-ec6f7a55bc87.png)

As you can see the text is quite a bit darker than on your Windows 10 machine. That's a bit unexpected to be honest and I didn't notice that in my VM. I'll see what I can do about this tomorrow.

**Comment by CrendKing** [comment]
I'm fine if the behavior on Windows is the same as on your Linux. Thanks!

**Comment by bastimeyer** [comment]
The issue is the horrendous text rendering engine of Windows (in Chromium).
Both builds share the same stylesheets, but I guess I will have to add platform dependent fixes now. This is a shame and should not be happening... :weary:

**Comment by CrendKing** [comment]
Yeah. For example, `-webkit-font-smoothing` is probably the most important related style. Unfortunately, I think it is only implemented in Linux and Mac, not Windows. This one CSS style prevents me from using [Atom](atom.io) on Windows.

**Comment by bastimeyer** [comment]
The ugly font rendering on Windows is caused by semi-transparent text colors. Chromium doesn't seem to like this at all. I thought their DirectWrite implementation had fixed those issues a couple of years ago.

Semi-transparent text colors were introduced by the implementation of themes roughly a year ago in d6527b1a87a6c9437365177ec9bad0af034797ce.

That means that I will have to rewrite all the stylesheets, so that only non-transparent font colors are being used instead. This is quite troublesome and I hope it won't be too much work.

Actually, my plan was implementing a more dynamic theming system with css variables that can be changed on runtime by the user (enabled by #275). I'm not entirely sure, but I think it would be wiser to wait for this first.
