### ISSUE TITLE
High CPU Usage on Mac

### ISSUE THREAD

**Issue by ysolovyov** [bastimeyer/livestreamer-twitch-gui#234]
### Description

High cpu usage of nwjs process while watching streams on source/high/medium quality, on source quality - up to 90% usage cpu.
### Expected / Actual behavior

Expectig low cpu usage, because now there is no point to watch streams in this app - better to use Safari with html5 - there I'm having 10-15% cpu usage on source quality.
### Reproduction steps
1. Just run the stream and watch cpu usage
### Environment details (operating system, etc.)

OS X El Capitan 10.11.4, VLC 2.2.2 x64
### Comments, logs, screenshots, etc.

<img width="225" alt="screen shot 2016-04-03 at 02 09 32" src="https://cloud.githubusercontent.com/assets/681814/14229662/cbda31f6-f941-11e5-8f67-7bfecad171c0.png">

**Comment by bastimeyer** [comment]
It's a known issue with NW.js `0.12.x` on some OSX machines... nwjs/nw.js#4508
I can't do anything about this. An upgrade to `0.13.x` is not possible right now.

**Comment by mobiuscoffee** [comment]
I have a similar issue on an ASUS Windows 10 laptop, except a bit more extreme. CPU usage will go up to 130% and cause my computer to start overheating.

Only started happening a few days ago.

**Comment by staffordr** [comment]
I have a similar but slightly different issue. Wondering if anyone else is having issues after upgrading to Sierra?

Everything was working fine for me on El Capitan, but since upgrading to Sierra, all hell has broke loose. VLC now uses ~50% CPU usage constantly and LiveStreamer's "energy impact" is around 133. In comparison, a single stream open in Safari has an "energy impact" of ~50. Bummer as I prefer the stream open in VLC even if I'm not saving resources.

**Comment by ysolovyov** [comment]
@bastimeyer which version it will be released in?

**Comment by bastimeyer** [comment]
The next one. Not sure when, though. Maybe a couple of days, needs some final tweaks.
This will also hopefully be the last release before I move the repo to streamlink.
