### ISSUE TITLE
Check for already open chat window

### ISSUE THREAD

**Issue by MrLint** [bastimeyer/livestreamer-twitch-gui#240]
Is it feasible to check if a chat window is open in the browser when launching a stream (if the open chat automatically is set) instead of opening another?

**Comment by bastimeyer** [comment]
Which chat method are you using?
Right now, the GUI does not keep track of the chat sub processes which it spawns. Something like that could be implemented, but I don't think this is the right approach. Chatty for instance has a `-single` mode, which detects already running instances while launching multiple processes. The parameters of the new one will be passed over to the already running process and then the new one will terminate. In this case, the GUI would not be able to detect already opened chat windows.

**Comment by MrLint** [comment]
Thanks for answering. I should have added that. I'm launching Twitch chat via Chrome. The only thing I can think of to handle that would be to check the open window list of the target app and compare the window names with the name of the stream you are connecting to. I suppose the OS could be told to bring that window front, however given each browsers semantics it would likey be a pain to try and issue a refresh (for instance) as each browser would have to have its own specific command. I guess alternatively if the steam could be launched with video only like there is the 'open chat' menu item.

**Comment by bastimeyer** [comment]
> I guess alternatively if the steam could be launched with video only like there is the 'open chat' menu item.

yeah, this could work

**Comment by MrLint** [comment]
Thank you for your attention.

**Comment by bastimeyer** [comment]
I decided against adding another entry to the context menu, as I don't want to bloat it up unnecessarily, so I added a checkbox to the settings menu instead. The "don't open chat twice" decision is being made once by the user, so there's no need to do this in the context menu logic.

I'm closing this issue, although it's not really been resolved, because there is no way of fixing this issue, unless the GUI does include its own chat client.
