### ISSUE TITLE
Setting to change the size of game icons/images in Top Games

### ISSUE THREAD

**Issue by Xesyto** [bastimeyer/livestreamer-twitch-gui#247]
----

### A Setting to change the size of the images for games in the Top Games page.

I'd like to be able to see a few more tiles on a page,  fullscreened on my second monitor i can just see three rows of 5 thats worse than twitch.tv/directory . Doesn't have to look exactly the same as twitch itself ofcourse but an option would be apreciated.
...

**Comment by bastimeyer** [comment]
I can't add hundreds of customizations to every component of the application. The StreamItemComponent already is ridiculously complex and I don't want to do the same with the GameItemComponent.

I also don't think the game tiles are too big. They need to have a certain size, so that the text doesn't get cut off in windowed mode. If you are looking for a specific game, then you should follow it instead of displaying everything at once.

If you still want smaller sizes, you can build the application on your own with modified sizes.
Here's a patch that increases the number of elements per row by one on the smallest window size:
[GameItemComponent.less.patch.zip](https://github.com/bastimeyer/livestreamer-twitch-gui/files/254594/GameItemComponent.less.patch.zip)

Build instructions can be found [here](https://github.com/bastimeyer/livestreamer-twitch-gui/tree/v0.13.0#build) or [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.13.0/CONTRIBUTING.md#developing-and-building)
Apply the patch with `git apply GameItemComponent.less.patch`
