### ISSUE TITLE
Unable to view stream with delay

### ISSUE THREAD

**Issue by Nycrea** [bastimeyer/livestreamer-twitch-gui#249]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Description
If the streamer has set a delay on his stream, livestreamer reports "no streams found on this url"

### Expected / Actual behavior
Play the stream as normal.

### Reproduction steps
Try to watch a streamer who has delay. 

### Environment details (operating system, etc.)
Windows 10

**Comment by bastimeyer** [comment]
This has nothing to do with *Livestreamer __Twitch GUI__*...
The "no streams found on this url" error message you're seeing is just the result of parsing the output of __*Livestreamer*__ which couldn't open the stream. This may happen either because of your connection to Twitch or because the stream simply went offline and is not accessible (anymore). Remember, that the GUI is basically just a helper tool for you to build the Livestreamer command line. Anything Livestreamer related does not belong here. If it doesn't work with the Livestreamer CLI, don't expect it to work in the GUI either.

Also, reproduction steps are not supposed to be a summary of the reported issue. These should be explicit steps instead, so developers are able to find issues in their software.
