### ISSUE TITLE
Pick server

### ISSUE THREAD

**Issue by EderO** [bastimeyer/livestreamer-twitch-gui#250]
Is there any way to chose a different twitch server?, like: http://www.crx4chrome.com/down/15871/crx/

Great program!!!

**Comment by bastimeyer** [comment]
Not possible (right now).
The Twitch.tv plugin of Livestreamer doesn't support choosing different servers via command line parameters. This has already been requested over at the Livestreamer repo.
See https://github.com/chrippa/livestreamer/issues/94#issuecomment-213859115 (excerpt of the chrome extension's source code)

I will add this to the GUI as soon as it's supported by Livestreamer.
I'm not sure if this will ever be supported though, since these server lists are static and everything could break as soon as Twitch changes the DNS records for these servers.

**Comment by Robby-** [comment]
I hate to say it, but the livestreamer project seems to be no longer actively maintained by its author (as can be seen from the lack of issues being fixed, commits being made, chrippa himself not commenting anymore, and the latest release which is dated well over a year ago), so it will probably never be supported, unless someone forks the project and maintains it. The day Twitch makes an API breaking change is not one I look forward to, as it will mean that we won't be able to watch streams anymore using this Twitch GUI and our favorite players, which depend on the livestreamer program.

**Comment by Izopi4a** [comment]
i really really want that. For some of my internet providers i got twitch lags with 50 + mbps speed. Very unfortunate its not possible :(

**Comment by bastimeyer** [comment]
It's against the [ToS of Twitch](https://www.twitch.tv/p/terms-of-service), so I'm afraid this won't be added to either streamlink and/or the Twitch GUI. If you think this is not violating the ToS, please comment in this thread streamlink/streamlink#91.

Also, I'm not sure if a feature like this would be stable enough, even if it was not restricted. What this chrome extension does is replacing the hostname of the HLS stream url with a static list of different hostnames. This means that as soon as Twitch alters their server infastructure and hostnames get changed, this feature will break.

The static hostname list can be found in the `bg.js` file of the `.crx` chrome extension file which was linked above (needs to be decompiled, just google for a crx decompile service).

You can get the HLS stream URL of a channel by running
`streamlink --player-passthrough hls --stream-url twitch.tv/CHANNEL best`

As you can see, the hostnames can be matched by this regular expression:
`^video-edge-([a-f\d]{6})\.([a-z]{3}\d{2})\.hls\.ttvnw\.net$`
The first capture group is a unique server ID (6 digit long hexadecimal ID) and the second one is a sub-network name (eg. fra01 for Frankfurt am Main in Germany).

So in order to find a working server for your connection, you need to know both the ID and the network name. The network name is predictable, but the ID definitely is not.

**Comment by Izopi4a** [comment]
yea, i spend the last hour or so reading about this , and yes i am screwed ... for now i set up an VPN between providers, so everytime i want to watch i stream i use my vpn. 

But i do believe that twitch has some major issue or choosing which server to provide. 

I tried setting up the url myself but it dint quite work. 

Anyways thanks for the great app you made ;-)
