### ISSUE TITLE
In-line stream controls in "You're watching" page

### ISSUE THREAD

**Issue by velit** [bastimeyer/livestreamer-twitch-gui#251]
### Feature enhancement description

Accessing the stream controls for streams requires the user to click the "Open dialog" button for every stream. I think it would be beneficial if these controls were in-lined in the "You're watching" page. It takes less clicks for the user to open the chat or change the stream quality. Furthermore when a user comes in for a quick opening of the stream chat they can't even minimize twitch gui because the pop-up control element overrides the window controls (minimize, maximize, close).

If the in-lining is done below the current screencap of the stream it won't even take horizontal space meaning the change wouldn't negatively impact small screen users other than potentially requiring them to scroll down more.

If nothing else and regardless what the specific implementation would it be possible to in-line at least the most used of the control elements like stream quality, opening twitch chat and closing the stream.

**Comment by bastimeyer** [comment]
Thanks for the suggestion!

The "open dialog" button was added when the other buttons (chat, share, etc.) were not component-based and adding those instead meant bloating the WatchingController with repetitive implementations.
This has all been fixed several months ago and I kind of forgot to add those buttons there.

I don't want to include the follow and subscribe buttons in the watching list though, since these are most likely to be misclicked. Having a "open dialog", a "close stream", an "open chat" and a "share channel" button is fine, IMO.

**Comment by velit** [comment]
Impressive responsiveness!
