### ISSUE TITLE
When building, qunit test fails - PhantomJS timed out

### ISSUE THREAD

**Issue by ProfessorKaos64** [bastimeyer/livestreamer-twitch-gui#254]
### Description
Issues building application on Debian Jessie

### Expected / Actual behavior

When building, qunit test fails - PhantomJS timed out. I have no idea why this is timing out. At first I thought this was due to me using pbuilder inside a chroot, but it fails using debuild too. This is during the run of `grunt release`. 

### Reproduction steps

1. Build either using the debian files below and debuild or using the main steps in the readme of this repository

### Environment details (operating system, etc.)

* Debian 8, debuild.
* [Debian files](https://github.com/ProfessorKaos64/LibreGeek-Packaging/tree/brewmaster/livestreamer-twitch-gui/debian)

### Comments, logs, screenshots, etc.

Using debuild
```
Running "qunit:all" (qunit) task
Testing http://localhost:8000/test/tests.html 
>> PhantomJS timed out, possibly due to a missing QUnit start() call.
Warning: 1/1 assertions failed (0ms) Use --force to continue.

Aborted due to warnings.
```

Building from this repository (manually):

```
Running "qunit:all" (qunit) task
Testing http://localhost:8000/test/tests.html 
>> PhantomJS timed out, possibly due to:
>> - QUnit is not loaded correctly.
>> - A missing QUnit start() call.
>> - Or, a misconfiguration of this task.
Warning: 1/1 assertions failed (0ms) Use --force to continue.

Aborted due to warnings.
```

**Comment by bastimeyer** [comment]
Are all npm and bower dependencies installed correctly?
Running `grunt test --debug` may give you some informations why PhantomJS failed, but sometimes it's not logging everything. You can also try to run `grunt connect:test:keepalive` and open `http://localhost:8000/test/tests.html` in your webbrowser to see what's happening, although it's a different env then.

**Comment by miko007** [comment]
i had the same problem.
simply doing `bower install ember` and selecting version `2.4.1` by hand worked for me (you have to run `grunt release`again)

**Comment by bastimeyer** [comment]
> selecting version 2.4.1 by hand

???
I don't see any version conflicts.

```bash
cd livestreamer-twitch-gui
rm -rf node_modules src/vendor
npm cache clean
bower cache clean
sudo npm install -g grunt-cli bower
npm install
```

This should work without conflicts.

Even if there were conflicts, bower should resolve these by installing the versions defined in the bower.json file by passing `--config.interactive=false` to the install param (see [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/7381adbabcc597c6c5541d6d697d67a04277fc60/package.json#L38)). This does of course only work when executing `npm install`, but the config parameter could be added to the bower.json file instead, so it'll work with a simple `bower install` call, too.

**Comment by CatLover91** [comment]
I am running ubuntu 15.10 and I too have encountered this issue. 

I may be abusing permissions? In order to install ember I had to execute:
`sudo bower --allow-root install ember` and that did not work. running the commands @bastimeyer recommended brings me back to the issue in the bug report (although I did need to use `sudo` for the `npm install` step though, idk if this is an issue)

**Comment by bastimeyer** [comment]
> sudo bower

Why are you running bower as root? Bower is meant to be run as normal user, because it installs the packages locally. [Never run bower as root...](http://bower.io/docs/api/#allow-root)

Npm is different, because by using the `-g` parameter, packages can be installed globally. Usually, these are packages with additional CLI stuff (like bower or grunt-cli), so they can be accessed globally from `$PATH` (`/usr/bin` or `/usr/local/bin`) instead of `$PWD/node_modules/package_name/bin`.
See `npm help install`, `npm help folders` and `npm help cache`.

Running npm as root also uses a different cache folder in `/root/.npm` (since it's using `$HOME/.npm` as default configuration), so write permission issues should not occur. If you're having those issues, then you did something wrong earlier or your config is messed up.
Run this to fix your permission issues: `sudo chown -R USERNAME:GROUPNAME ~/.npm ~/.cache/bower`
