### ISSUE TITLE
Feature request: Auto-hiding of desktop notifications

### ISSUE THREAD

**Issue by adamhab15** [bastimeyer/livestreamer-twitch-gui#260]
Hello.
Would you consider adding the option to have the notifications go away by themselves after x seconds?
It would save me having to get up and move the mouse, or turn off the feature entirely, which I'd rather not do.

**Comment by bastimeyer** [comment]
Notifications are rendered by your operating system and are independent from any application. It's the fault of your OS (or desktop environment) if notifications are not being faded out.

Since you ignored the issue template :angry: and didn't provide any details about your OS, I'm guessing you're using Win7 and you're talking about balloon tooltips in the system tray bar...
Win7 doesn't have a system-wide notification manager, this was introduced by Win8 with toast notifications, so by using Win7, tooltips are the only way of displaying "homogeneous" system notifications.

This *could* be improved by having a dedicated notification manager application installed, like [growl](http://www.growlforwindows.com/gfw/about.aspx) for instance, and the GUI having a dedicated implementation for this specific program. I don't know if I want to do this, though, since this is an edge case of this specific OS and an implementation for any kind of these programs would be required.

**Comment by adamhab15** [comment]
I am indeed talking about the w7 balloons, I guess I'll have to upgrade to 10.
Thanks for this amazing application.
