### ISSUE TITLE
Info Bar in "Followed Games"

### ISSUE THREAD

**Issue by dingsbums** [bastimeyer/livestreamer-twitch-gui#262]
Hey,

would it be possible to show stream title in "Followed Games"? In Settings I chose "game being played" to see the game title in "Top Channels". That is unnecessary in the games section. 

Thanks

**Comment by bastimeyer** [comment]
This has nothing to do with the "followed games" menu, it also affects the "top games" menu. The "game being played" info [is always hidden](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/97218d74e94565a1856f616b13efe5f49be229fc/src/templates/games/GamesGame.hbs#L11) (`showGame=false`) in the `GamesGame` route.

It doesn't matter if you're having this option selected in the settings, the bottom bar of stream items in these menus will never be shown, because it's unnecessary, like you've already said.
You can still see the stream title by hovering the preview image or by expanding the stream info in the bottom right corner of the preview image.

Adding an exception to the `GamesGame` route for this specific configuration will confuse the user, since it'll basically reverse the logic of this setting, and I don't think this is a good idea.
