### ISSUE TITLE
Cannot automatically login to Chatty via Livestreamer Twitch GUI

### ISSUE THREAD

**Issue by mikhail21393** [bastimeyer/livestreamer-twitch-gui#267]
### Description
I was able to login to Chatty automatically using Livestreamer Twitch GUI, but last time I checked when I upgraded to the latest version it didn't work for me.

### Expected / Actual behavior
Chatty opens automatically (my choice of course) when I set it up with certain parameters that worked for me the last time.

### Reproduction steps
1. Chat Method: Custom application/Chat application: javaw -jar "C:\Program Files\Chatty\Chatty.jar" -connect -single -channel {channel}
2. Open chat: Automatically open chat: ticked
3. Launch a stream

### Environment details (operating system, etc.)
Windows 7 x64 
Chatty 0.8.3
Livestreamer Twitch GUI 0.14.0

### Comments, logs, screenshots, etc.
![capture](https://cloud.githubusercontent.com/assets/2913427/16800093/32c305dc-48fc-11e6-832b-58490881ef7e.PNG)

Well! That was the most frustrating part I've seen for a while, a username with slashes and after removing some settings from Chatty in Windows Explorer it seems that it wasn't this issue after all.

I hope I saved you guys some time for researching this particular issue.

Thanks in Advance!

**Comment by bastimeyer** [comment]
> Chat Method: Custom application/Chat application: javaw -jar "C:\Program Files\Chatty\Chatty.jar" -connect -single -channel {channel}

You're not using any auth parameters in your custom chat command, so how is Chatty supposed to know your login data?
You were probably logged in, because Chatty stores the previously used login data and will use it for a certain time when not setting any login data.

See what the GUI is doing when selecting the Chatty method:
https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.14.0/src/config/chat.json#L68

To fix your issue, either choose the Chatty method in the GUI or add the needed Chatty parameters...

If you want to keep your custom command instead, add quotation marks around the `{channel}` variable, because otherwise, the GUI will escape every character (as seen in your screenshot).

**Comment by mikhail21393** [comment]
Yes I am aware that I am not using any auth parameters, because I've used tokens from Twitch page for both Chatty and Livestreamer Twitch GUI and never faced this problem before, but thanks to you I will keep this bug report as a reference as it might be useful to me and to other people.

Thank you for the quick response! Be well!

**Comment by bastimeyer** [comment]
> I've used tokens from Twitch page for both Chatty and Livestreamer Twitch GUI

Livestreamer Twitch GUI will use the same oauth token it uses itself for Chatty when using the "Chatty" chat method in the settings dropdown, so there is no need to login a second time.

Your issue was not correctly quoting the variables. There's a tooltip in the GUI that warns about this, but I think I should make this more visible somehow.
