### ISSUE TITLE
Error: Couldn't launch the stream / Timeout

### ISSUE THREAD

**Issue by lostcossack** [bastimeyer/livestreamer-twitch-gui#268]
Hey,

after updating to .14 on Windows 7 I cannot start streams anymore. When I try to start a stream livestreamer says "Preparing Please Wait..." and after about 10s "Error: Couldn't launch the stream" and "Timeout" as the reason. Before that VLC would pop up within a few seconds. I've tried different versions since with the same result. I made sure he finds all the paths he needs, to no avail.

http://puu.sh/q0fiF/bd1892d9b8.png

Any ideas?

**Comment by bastimeyer** [comment]
Did you set a custom livestreamer path in the settings? If a custom path is not set, the GUI will try to find the livestreamer executable in each directory listed in the `$PATH` environment variable, which is the default behavior and works on all correctly set up systems. If it cannot find an executable, it'll check [these fallback paths](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.14.0/src/config/livestreamer.json#L5-L6) before finally giving up.

When the livestreamer executable was found, the GUI will first validate it before the stream can be launched. This means that livestreamer will be executed twice, first for checking the used version and then for opening the stream.

Having a timeout during the validation does only happen if [there was no output at all](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.14.0/src/app/services/LivestreamerService.js#L316). This can happen if you're executing a different application, or if your system was unable to load livestreamer in time (maybe due to slow read performance of your file system).

Please make sure that you're running the correct livestreamer executable (run `where livestreamer` on Windows to check this) and that the [validation time](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.14.0/src/config/livestreamer.json#L19) is enough for your system to load livestreamer.

The validation logic was not changed in v0.14.0, there were some code refactorings though, and the windows fallback paths were added in addition to osx and linux. That's why I assume that there's something wrong with your configuration.

**Comment by lostcossack** [comment]
Yes, I've set a custom path to pinpoint the livestreamer executable. If I don't (i.e. leave it on default) he prompts me to (re)install livestreamer because he can't find it (I have two disks with the bulk programs on D:).

Apparently I'm also missing large chunks of the src contents like the livestreamer.json you mentioned. Is the config directory supposed to be in the %appdata%?

**Comment by bastimeyer** [comment]
This sounds like you didn't install livestreamer correctly. Please [see the readme](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.14.0/README.md#notes), which says that you should install livestreamer on Windows via the installer. This way, the installation directory will be added to the `PATH` env var, so that the GUI can find it automatically.

No, you're not missing anything. The conf files are more like compile vars and are embedded into the application content via requirejs. If you want to change anything there, then you need to compile the application for yourself.

Since you've set a custom path, you should run this to see why you're getting a timeout in the GUI:
`/your/custom/path/to/livestreamer.exe --version --no-version-check` (see [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.14.0/src/app/services/LivestreamerService.js#L281))
If this doesn't output anything or results in an error (either via stdout/stderr or return code > 0), then you know the source of your issue...

**Comment by lostcossack** [comment]
The clean re-install fixed it. I didn't realize the GUI and Livestreamer were two different pairs of shoes.
Thanks for the help!
