### ISSUE TITLE
Unable to open chat through Google Chrome or Chromium

### ISSUE THREAD

**Issue by mainmango** [bastimeyer/livestreamer-twitch-gui#269]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Description
Ever since I upgraded to 0.14.0 I'm unable to launch chat with Google Chrome or Chromium. If I click the chat bubble it doesn't respond. If I select Default Browser it will open with Google Chrome but with all my bookmarks, address bar etc.
...

### Expected / Actual behavior
It should open a Google Chrome window but with no address bar, bookmarks and etc.
...

### Reproduction steps

1. ... Set chat metyhod to Chromium or Google Chrome
2. ... Attempt to open chat either through the popup icon, or context menu.
3. ... Nothing happens

### Environment details (operating system, etc.)

... Windows 10. It works perfectly fine last version.

### Comments, logs, screenshots, etc.

...

**Comment by bastimeyer** [comment]
I don't see anything wrong with the current implementation, and it's also working flawlessly in all of my Windows virtual machines. The logic did not change in the recent update (other than a simple code refactor).

Did you set a custom chromium/chrome executable path?
These are the fallback paths used when no path is set: [Chromium](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.14.0/src/config/chat.json#L17-L19) and [Google Chrome](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.14.0/src/config/chat.json#L46-L48).

Since the GUI doesn't check the Windows registry, there is no other way than defining a known set of installation directories (covered by environment variables). If you've installed Chromium/Chrome in a different directory, you need to set a custom path or else it won't work.

**Comment by mainmango** [comment]
Whoa..
At the time I had set a custom executable path directly to my Chrome.exe however I fixed the issue when I removed the file path and left it blank.

Thanks!
