### ISSUE TITLE
Can't open chat after 0.14.0 on Chrome if manually inputting path to executable

### ISSUE THREAD

**Issue by skinner79** [bastimeyer/livestreamer-twitch-gui#270]
### Description

After the update to 0.14.0, I can no longer open the chat window for any channel on Google Chrome if I input the path to the Chrome executable location in the options menu. After testing I found out that leaving this input blank fixes the issue. This same chat function was working perfectly fine before this update.

### Expected / Actual behavior

Open chat on Chrome if you manually input the path to the executable file. 

### Reproduction steps

- Go to Settings > Chat
- Choose Google Chrome as Chat Method  to open Chat.
- Manually input the path to the location of the Google Chrome executable.
- Apply the settings.
- Click on the chat icon when a stream starts = doesn't work
- Right click on the thumbnail of a stream, click on open chat = doesn't work
- Tick on settings the option to open chat automatically = doesn't work

### Environment details (operating system, etc.)

Windows 8.1 64 bit. I am using the 64 bit version of Livestreamer Twitch GUI.

My Chrome path = C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

### Comments, logs, screenshots, etc.

I've updated to 0.14.0 by just copying the files on top of the old ones. I have always done this and I had no problems until this update.

**Comment by skulblakka** [comment]
Seems like you are not the first one experiencing this behavior (#269)

**Comment by skinner79** [comment]
Sorry, I forgot to search the closed issues. However I don't believe this issue should be closed because the behavior of opening chat when you manually input a path to chrome is still not working on 0.14.0.

**Comment by bastimeyer** [comment]
Thanks for reporting.
The issue was introduced by 399576f. Setting a custom path when choosing Chromium or Google Chrome does not work in v0.14.0.

The previous issue was closed because there were no informations provided. I will keep this one open until the next release, but I'm not sure if I want to release a hotfix for this soon, since this issue can be prevented by leaving the custom path empty.

**Comment by Glog78** [comment]
The problem is that custom chat application doesn't work either. /usr/bin/chromium --app={url} which worked before is now broken. I prefer chromium in app mode just because it makes a pure little chat window.

**Comment by bastimeyer** [comment]
> /usr/bin/chromium --app={url}

Since the implementation of the new parser/tokenizer, all variables need to be inside quoted strings.
This works: [`chromium "--app={url}"`](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.14.0/src/config/chat.json#L3)

As I've already said in the other thread, I should have made this more obvious, the tooltip on the "Available variables" text in the GUI is not enough. I will need to add this to the wiki, too.

The variables parser, tokenizer and substitution logic was changed (see 9eac3b4) because of the `--player-args` livestreamer parameter. Having custom player window titles with channel data was sometimes being escaped incorrectly, since it was based on a static set of characters. The substitution logic was changed so that it will either escape all characters when not using quotation marks around variables or it will use the same quotation mark used at the beginning of the string (which is the expected behavior).

Players like `vlc` or `mpv` will correctly parse their parameters with escaped characters (`mpv --title \f\o\o\ \b\a\r file`), but chromium does not, that's why you're encounting an error.
