### ISSUE TITLE
Cannot follow games that have dots in the name

### ISSUE THREAD

**Issue by Robby-** [bastimeyer/livestreamer-twitch-gui#273]
### Description
When clicking the follow button for a game, the icon shakes left and right and the game is not added to the followed games list. I tried to follow the game called `Plague Inc.` and it didn't work, thinking it may be a temporary issue with Twitch I then clicked another game to try, like `Counter-Strike: Global Offensive`, and this worked. Then I started thinking, maybe it's because of the dot in the name, so I looked for another game that has dots in the name and came across `M.U.G.E.N`, tried to follow that game and it didn't work. So, it seems it's something to do with the dots.

### Expected / Actual behavior
Expected: It should just work and add the game to the followed games list.
Actual: It fails to add the game, the icon shakes left and right to indicate failure.

### Reproduction steps
1. Attempt to add a game with a dot in the name to the followed games list.
2. Watch it fail to do that.

### Environment details (operating system, etc.)
Windows 7, 64-bit.

**Comment by bastimeyer** [comment]
Thanks!
The issue was caused by Twitch and a change of their private API for following and unfollowing games...

It used to be
**findRecord:** `GET https://api.twitch.tv/api/users/:username/follows/games/:id`
**createRecord:** `POST https://api.twitch.tv/api/users/:username/follows/games/:id`
**deleteRecord:** `DELETE https://api.twitch.tv/api/users/:username/follows/games/:id`

but was changed to
**findRecord:** `GET https://api.twitch.tv/api/users/:username/follows/games/isFollowing?name=:id`
**createRecord:** `POST https://api.twitch.tv/api/users/:username/follows/games/follow (DATA name=:id)`
**deleteRecord:** `DELETE https://api.twitch.tv/api/users/:username/follows/games/unfollow?name=:id`

The findRecord method was already changed in v0.14.0, but the other ones were working correctly on all the other games, so I assumed it was still valid... Since it's a private API, they will change it without deprecating anything first, so it can break without any announcement. I don't understand this change, to be honest. They are breaking common http API structures with it. It's terrible...
