### ISSUE TITLE
Filter out streams not work if check 2 languages

### ISSUE THREAD

**Issue by germetist** [bastimeyer/livestreamer-twitch-gui#281]
If checked Filter out streams and choose 2+ languages, filter not work
### Actual behavior
![livestreamer-twitch-gui_2016-08-04_18-30-22](https://cloud.githubusercontent.com/assets/4971258/17400511/89fd7a9e-5a72-11e6-9d6f-1d79758e99ac.jpg)
### Expected  
List of streams on Russian and English languages
### Reproduction steps
1. Open Setting
![livestreamer-twitch-gui_2016-08-04_18-40-25](https://cloud.githubusercontent.com/assets/4971258/17400589/fa24269c-5a72-11e6-8e8f-e353447f21c1.png)
2.  LMC Langeages
![livestreamer-twitch-gui_2016-08-04_18-40-52](https://cloud.githubusercontent.com/assets/4971258/17400616/12c9ea6a-5a73-11e6-9ed5-7d2df85800fd.png)
3. Check Filter out streams checkbox
![livestreamer-twitch-gui_2016-08-04_18-41-33](https://cloud.githubusercontent.com/assets/4971258/17400627/28e02c74-5a73-11e6-9d55-fb88fee99619.png)
4. Check Russian(ru) and English(en) checkbox
![livestreamer-twitch-gui_2016-08-04_18-43-14](https://cloud.githubusercontent.com/assets/4971258/17400677/65155962-5a73-11e6-8372-590bc5b63076.png)
5. Click Top Channels
![livestreamer-twitch-gui_2016-08-04_18-43-47](https://cloud.githubusercontent.com/assets/4971258/17400696/7c753ab4-5a73-11e6-9ad8-0dd9628eeb0d.png)

### Environment details (operating system, etc.)
Windows 10 pro x64
livestreamer twitch gui 0.14.0

**Comment by bastimeyer** [comment]
This is a limitation of the Twitch API. Filtering multiple languages was working in the past, but got removed at some point. Don't ask me why they decided to remove this. There already was a discussion about this here, see #151.

That's why I added this text here:
![screenshot from 2016-08-04 14-06-26](https://cloud.githubusercontent.com/assets/467294/17401226/bad5bd28-5a4c-11e6-87bb-27caebb1519d.png)
