### ISSUE TITLE
settings -> livestreamer -> hls live edge (and other number boxes) broken on os x

### ISSUE THREAD

**Issue by xaxxon** [bastimeyer/livestreamer-twitch-gui#282]
_Thanks for reporting an issue!_
_Please read the contribution guidelines first!_

_Feel free to use the following template. Be as detailed as possible._
_Don't forget to remove this text before submitting._

---
### Description

When changing the value in settings for numeric fields in os x, the up/down arrows in the input box don't do anything.   Also, clicking in the box and using the track pad to scroll up/down is very broken.   It seems to be able to scroll one direction after clicking, but the number shoots up/down so fast and then the page starts scrolling.   Presumably this is the same trackpad interaction issues as the problem with smooth scrolling was.   This functionality should probably be disabled on OS X and then the up/down arrows should be fixed.

Entering a number via keyboard works fine.
...
### Expected / Actual behavior

...
### Reproduction steps
1. ...
2. ...
3. ...
### Environment details (operating system, etc.)

os x, chrome -- latest stable everything    14.1 livestreamer
...
### Comments, logs, screenshots, etc.

Thanks so much for making this!   Still loving it!
...

**Comment by bastimeyer** [comment]
These input fields are default HTML5 [number fields](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.14.1/src/templates/settings/SettingsLivestreamer.hbs#L47) and there are no additional event listeners of any kind added to them, so this has nothing to do with smooth scrolling. It's Chromium which is adding these features to the number fields.

This issue seems to be related to the used Chromium version of NW.js, which is a little bit old (NW.js `0.12.3` -> Chromium `41.0.2272.76`) compared to one of the new Chrome releases (52/53/54). An upgrade to a new NW.js version could fix this (#275), but I'm not sure.

Also, scrolling on top of the number fields doesn't do anything for me in my OSX VM (I don't have a trackpad, though). Using the arrow keys on the keyboard does work, clicking the arrow buttons inside the field is indeed broken.

**Comment by xaxxon** [comment]
With regards to the smooth scrolling, I was referring to the rate at which
the numbers change when scrolling in the number box.   it's very jerky like
the smooth scrolling is/was.

https://www.youtube.com/watch?v=DCiM0aP5QNw

Everything in that movie is with the trackpad (pretty sure -- at least
almost all of it).  The seemingly random times when the number changes is
the trackpad.

--Zac
