### ISSUE TITLE
Turning off notifications does NOT work

### ISSUE THREAD

**Issue by Alahadi** [bastimeyer/livestreamer-twitch-gui#286]
I have notifications turned off but I am still getting desktop notifications. I tried restarting the program/pc and still I get these[STATUS] msg boxes

**Comment by bastimeyer** [comment]
Without any informations I'm not able to understand what you are talking about, on which OS you are and what your configurations/settings are, because you completely ignored the issue template. There is no way for me to reproduce this.

Disabling desktop notifications in the settings menu will disable the NotificationService and the polling of new data from the Twitch API. This will ultimately prevent notifications to be shown. There's also the pause notifications checkbox in the tray icon menu, which works the same.
