### ISSUE TITLE
Does not have "proper window management in Ubuntu"

### ISSUE THREAD

**Issue by eXcuvator** [bastimeyer/livestreamer-twitch-gui#288]
---

Does not have "proper window management in Ubuntu"

...

So I'm not a linux pro, but usually all applications have proper window bars here. Instead, it has its own minimize and full screen icons. The problem arises when some linux flavors require the standard bar to be fully functionable.

In Kubuntu, right clicks on the application bar add a lot of features otherwise not available. For example, one can [bind applications to activities](http://unix.stackexchange.com/questions/45674/kde-how-to-bind-permanently-an-application-to-a-desktop-activity) (virtual desktops) using that. It would make sense to have a "watch esports" activity, and bind livestreamer to that. Since it's not possible, it will instead appear on every single screen while open.

**Comment by bastimeyer** [comment]
That's the issue of non-native applications like NW.js / Electron.
There is no way of having a consistent layout/look/feel among each OS and DE on Linux. Disabling the window frame simply makes more sense, since you are not using a toolkit with native styles anyway.

The window frame can be enabled [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.14.2/src/package.json#L9) if you want.

If KDE has issues with applications that prevent the window decorations from being shown, then there's nothing for me that I can do. It's working fine on other DEs and no-DE setups.

I think NW.js supports changing the frame settings during runtime, but implementing a quick toggle mechanism would also mean adding a change to the layout. I'm not sure if I want to spend time doing this.
