### ISSUE TITLE
Add zip file checksums to chocolatey package

### ISSUE THREAD

**Issue by scowalt** [bastimeyer/livestreamer-twitch-gui#294]
For all future submissions, chocolatey now requires checksums for all files downloaded from external servers. This is to prevent MITM attacks and compromised servers from feeding users bad executables.

I'm not quite sure how we'll implement this. It will involve updating the package templates to include the checksum field, and then expanding the grunt script to include calculating the checksums for the 32-bit and 64-bit executables

**Comment by bastimeyer** [comment]
For future releases I'm going to add a `checksums.txt` file which can be used by package configs that download the archives from the github releases page. I need to add this anyway, because of the internal update mechanism (which still needs to be finished).

Hash algorithm will be sha256 and the format `[sum]  [filename]`, so basically the same as the output of `sha256sum`.

I'll add a function to the `build/tasks/common/package` module that downloads this file and returns the desired hashsum. I'll notify you once I've done this, so you can upgrade the package:chocolatey task.

**Comment by bastimeyer** [comment]
Implemented in 6f18c5b...

I rewrote the package task for this, see the commit msg or diff.
There's a config file for the package task now.

The hashes can be accessed via `<%= package.checksums.win64 %>` from the grunt config in the templates. The [checksums option](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/6f18c5b048a938d9eeba4b4beebce47acb9b3fec/build/tasks/configs/package.js#L14) needs to be enabled for this, though... I also added the same behavior for the changelog.

Please remember that the current release doesn't have a checksums file attached. If this is necessary, let me know and I'll add it.
