### ISSUE TITLE
SmartScreen filter notice remains open after selecting "Run Anyway"

### ISSUE THREAD

**Issue by brettpatterson** [bastimeyer/livestreamer-twitch-gui#296]
### Description

SmartScreen after Windows 10 Anniversary update remains open even though I clicked "Run Anyway".

### Expected / Actual behavior

Expected behavior is to have the SmartScreen filter disappear and the app launch.

Actual behavior is the app launches but the SmartScreen filter notice remains.

### Reproduction steps

1. Use Windows 10 Anniversary Edition
2. Launch Livestreamer Twitch GUI
3. Click "Run anyway" button

### Environment details (operating system, etc.)

Windows 10 Anniversary Edition x64
Livestreamer Twitch GUI x64

### Comments, logs, screenshots, etc.

![smartscreen-filter-stays-after-launch](https://cloud.githubusercontent.com/assets/15036826/17719794/3a146b82-63eb-11e6-830e-7e5408560cf9.png)

**Comment by bastimeyer** [comment]
I can't reproduce this behavior in a fresh win10 VM...
NW.js creates a couple of child processes when it's being launched. Maybe that's the issue here.

The reason why you're seeing this message is that the Windows builds are not signed. The NW.js executable itself is signed (I believe), but it doesn't matter, because the app content is being appended to the executable by the nw-builder. The builds need to be signed again, but I haven't set this up yet. I simply don't have the time and interest in doing this right now, as it can be quite annying setting this up on Linux. It's at the very bottom of my priority list. I may set this up, once I've merged the windows-installer code.

If you don't want to see this message, disable the Windows smartscreen filter.

**Comment by brettpatterson** [comment]
If signing it will prevent the SmartScreen filter from showing, I'll just wait for it.  It only happens on initial launch of the program after download, so it's not that big of a deal.  I just had to open task manager and kill the "Windows SmartScreen" task that was sitting idle.
