### ISSUE TITLE
ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process

### ISSUE THREAD

**Issue by Radagast** [bastimeyer/livestreamer-twitch-gui#298]
### Reproduction steps

1. Extract the archive
2. Open terminal in extracted archive folder
3. run ./start.sh

### Environment details (operating system, etc.)

OpenSUSE Leap 42.1
Xfce 4.12.2
Kernel: 4.7.0-8
X.org: 1.17.2
radeonsi

### Comments, logs, screenshots, etc.

On launch I see

> [13077:0820/104041:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[13097:0820/104041:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process

Is this a problem?

**Comment by bastimeyer** [comment]
> [13077:0820/104041:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.

https://github.com/nwjs/nw.js/issues/2699#issuecomment-64603898
https://github.com/nwjs/nw.js/issues/4385#issuecomment-184094114
The NW.js devs removed the message in the new NW.js releases (`>=0.13.0`). The main focus here right now is an upgrade to one of these. See the progress here: #275 

> [13097:0820/104041:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process

According to the chromium bug tracker, this is/was a radeon related issue. I can't say anything about this, sorry...

> Is this a problem?

Since NW.js doesn't use a renderer sandbox, all these *warnings* can be ignored. If this is annoying, just redirect stderr to /dev/null. :hushed:

**Comment by Radagast** [comment]
Thanks for the reply. I don't use/have Chromium/Chrome installed, so I'd not seen the sandbox error before. Other than that, everything seems to be working correctly. I guess this can be closed.
