### ISSUE TITLE
Sequential clicks on 'Live streams' will show a stream or empty

### ISSUE THREAD

**Issue by MrLint** [bastimeyer/livestreamer-twitch-gui#314]
The 'Live Streams' items will show 'Followed streams (1)' but will say the list of followed streams is empty.

Clicking 'Live streams again' will show the thumbnail, a 3 click will go back to 'empty'

This behavior alternates every other click of live streams.
I have not yet been able to test when the number of live people is more than 1 yet.
![2016-09-15 17_52_47-livestreamer twitch gui](https://cloud.githubusercontent.com/assets/18565454/18568918/a8f441c8-7b6d-11e6-9663-8ef30811bc9f.png)

**Comment by MrLint** [comment]
This seems to have started with 0.15.0, Didnt experience this in .14

**Comment by MrLint** [comment]
"Channels" for which I have 16 items is alternating between the following 2 views every other time clicking on it consecutively.
![2016-09-15 17_59_55-](https://cloud.githubusercontent.com/assets/18565454/18569097/8a5b5dae-7b6e-11e6-8c0f-eab6a8a27397.png)
![2016-09-15 17_59_25-](https://cloud.githubusercontent.com/assets/18565454/18569096/8a5788e6-7b6e-11e6-8141-fc0c399c1359.png)

**Comment by MrLint** [comment]
Sorry for spamming all over this report, I have discovered that the 'alternate' (empty or smaller view) happens if click any of the items.

That is to say, I click 'live streams' and it shows the one live item, then hosted stream shows empty. Click hosted again, shows 2 steams, then click to live stream shows empty.

**Comment by bastimeyer** [comment]
Seems like the InfiniteScrollMixin doesn't reset properly, as it is requesting the wrong range of records on each second request. 70b1426 and the removal of `Ember.Binding` is responsible for this.
This sucks. I had to rush with the upload of two releases today/yesterday because of the API change that broke Livestreamer and didn't notice that this bug was included in the master branch. Unfortunately I don't have a test case for this.
The Twitch servers were instable the last couple of days and any time when this happens, API responses are empty sometimes. This is nothing new and has already happened multiple times over the past 2 years now. That's why I didn't notice that. That's also why it says "The returned list of followed streams is empty" instead of "You don't follow any channels".

I'll fix this tomorrow and will then upload *another* release. This is really annoying... 😭 

Until then, either live with this bug and reload twice, or go back to `v0.14.2`. The `0.15.x` releases are somewhat optional if you stay logged in to your Twitch account.

**Comment by bastimeyer** [comment]
https://github.com/bastimeyer/livestreamer-twitch-gui/releases/tag/v0.15.2
