### ISSUE TITLE
Choosing fps for streams

### ISSUE THREAD

**Issue by widestm** [bastimeyer/livestreamer-twitch-gui#332]
### Description

Choosing fps on stream
### Expected / Actual behavior

Now that twitch had added the option to pick quality and fps for streams that allows this it would be great with this also implemented in the gui when picking a quality. 

So being able to pick 720p@30 fps instead of 60fps for example.

Livestreamer seems to be able to do it already so it should mostly be a matter of adding the new options to the list.

**Comment by bastimeyer** [comment]
It is not as simple as adding these explicit quality names to the dropdown, because they are not available for every channel. It doesn't make sense having a list of qualities where a selection potentially doesn't match the list of available qualities of a channel. This especially doesn't make sense when having a default quality that's globally defined (or a channel specific default quality).

The quality names you're seeing in the GUI are actually presets for livestreamer with additional fallbacks, so all streams can be viewed, no matter what quality Twitch provides for the specific channel. The presets can be customized in the settings menu since v0.16.0 if you think you need to change them.

https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.16.0/src/app/models/LivestreamerQualities.js
