### ISSUE TITLE
Total beginner needs some help with player parameters with MPC

### ISSUE THREAD

**Issue by gnogas** [bastimeyer/livestreamer-twitch-gui#335]
### Description

Hi, first of all huge thanks for the program! Now my problem is that i can't quite wrap my head around player parameters, whenever i try to fiddle with them the player refuses to start and google wasn't really being a big help. So to be perfectly clear i would like to on the title bar of my MPC window be able to see;
Name of the streamer
Stream status (the titles the streamers usually have on the top)
Game being played

It would be a huge help if someone could point me towards the right direction for understanding this stuff or just straight up giving me the code would be even more appreciated.

Thanks in advance!

**Comment by bastimeyer** [comment]
Hi.
MPC doesn't support custom window titles. Running `mpc-hc -h` will tell you all available parameters. Google also gives you this link as the first result https://gist.github.com/vBm/88abddafd53706439c29
and you can also find all available parameters in the source code of the latest MPC HC release https://github.com/mpc-hc/mpc-hc/blob/1.7.10/src/mpc-hc/AppSettings.cpp#L2020-L2141 😀.

See the wiki for the most useful parameters for some of the popular players:
https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Player-configuration

When using VLC, you should set the player parameters to `--meta-title "{name} - {game} - {status}"` or even better to `--play-and-exit --no-one-instance --meta-title "{name} - {game} - {status}"`, so you don't run into issues with the default VLC configuration. Make sure to also set the player path to the executable, otherwise the GUI will reject the custom parameters.

**Comment by gnogas** [comment]
Thanks for the response. Shame about mpc not allowing custom titles, the reason why i prefer mpc is because of the option to stretch the stream to the entire window that i don't get with vlc. I have both set up right now so i guess i'll just have to make due!

**Comment by bastimeyer** [comment]
> stretch the stream to the entire window

I don't know why you would want to do something like this, but even VLC can do this. If you don't want to use VLC, you could try MPV, although I'm not sure if this is the right choice for the average Windows user.
