### ISSUE TITLE
stream seeking (mpv) ??

### ISSUE THREAD

**Issue by DragonzMaster** [bastimeyer/livestreamer-twitch-gui#341]
## Description
I'am using mpv, when the stream stops to buffer (due low bandwidth) or I puase player I can't seek and jump to live stream again
...

### Expected / Actual behavior
I could seek to latest part of stream (live)
...

### Reproduction steps

1. chosing streamlink, mpv as player 
2. start the stream
3. pause the player for period of time
4. try to seek/jump to live stream but can't
### Environment details (operating system, etc.)
win 10 64x
rtmp / HLS live edge = 3 / HLS threads = 3
...

**Comment by bastimeyer** [comment]
It's a setting in MPV that prevents you to seek when the input data is a video/audio stream, which is usually not seekable. See the [`--force-seekable`](https://mpv.io/manual/stable/#options-force-seekable) MPV parameter.

I guess this can be added to the new player presets.

**Comment by DragonzMaster** [comment]
Few days ago, I think when I set stream type to HTTP (or HLS - don't remember sorry) It sometimes works but not everytime as it jumps to start of stream instead .
I've tried the parameter (above) and it is also jumps to start o stream.

**Comment by bastimeyer** [comment]
This depends on the [seek method](https://mpv.io/manual/stable/#keyboard-control) ([input.conf](https://github.com/mpv-player/mpv/blob/v0.21.0/etc/input.conf#L47-L57)) you're using.
See the [`--hr-seek`](https://mpv.io/manual/stable/#options-hr-seek) and its related parameters.

This also depends on your MPV cache settings:
https://mpv.io/manual/stable/#cache

Here's a working example:
`streamlink twitch.tv/CHANNEL best --player-passthrough rtmp -p /usr/bin/mpv -a "--force-seekable=yes --hr-seek=yes --hr-seek-framedrop=yes {filename}"`

**Comment by DragonzMaster** [comment]
Thanks, Now I can seek through stream.
I hope it works with HTTP too.

**Comment by DragonzMaster** [comment]
Sorry for reopening this, but it often works but not every time as mostly it go back to start of stream.

**Comment by bastimeyer** [comment]
I don't know how I can help you here, seeking should work correctly with these parameters.

Please ask your question somewhere else (on the streamlink or mpv repo), as it is not really related to Livestreamer Twitch GUI, I'm just helping because I have the interest in providing a good default config for each player.

As I already said, these MPV parameters also depend on your [cache settings](https://mpv.io/manual/stable/#cache). You should only be able to jump to the start of the stream (T<=0) if you're using MPV's cache and a `--cache-backbuffer` which is big enough. Unless I haven't missed anything in the documentation, there's no "jump to the stream's head" function.

**Comment by DragonzMaster** [comment]
No problem, Thanks for your efforts any way.
