### ISSUE TITLE
Using Login Feature on different PCs

### ISSUE THREAD

**Issue by cirf** [bastimeyer/livestreamer-twitch-gui#36]
if i log in on different machines with this, i get an authorisation error on the other pc. At the moment i have to log in new every time if i logged in on another pc. If i only use one PC the login works multiple days. Maybe there is a workarround or new feature to prevent this from happening?

**Comment by bastimeyer** [comment]
It's because twitch deletes the OAuth token of your old login as soon as you login on a different machine, so the old session "expires".
There's not much I can do, that's simply how the oauth system works... :confused:

If this is super annoying for you, you could copy over the oauth token of the logged in machine to the second one.
Start the application with the `--remote-debugging-port=8888` parameter and open `http://localhost:8888` in your browser. Then run the following line to read your access token:
```js
JSON.parse( localStorage.getItem( "app" ) ).auth.records[1].access_token
```
On the other machine, do the same and run the following line to set the access token:
```js
var access_token = "YOUR ACCESS TOKEN";
var obj = JSON.parse( localStorage.getItem( "app" ) );
obj.auth.records[1].access_token = access_token;
localStorage.setItem( "app", JSON.stringify( obj ) );
```
Then restart the app, so it can do the auto-login procedure...
