### ISSUE TITLE
Unable to build from the master branch

### ISSUE THREAD

**Issue by brianpardee** [bastimeyer/livestreamer-twitch-gui#37]
Hey, bastimeyer. I'm trying to build from the master branch. I followed your instructions in the readme exactly and no go. I cloned the repository using GitHub's app. I ran the command prompt as administrator when trying to build.
I get this when doing the command "npm install"

C:\TWITCH\livestreamer-twitch-gui>npm install

> livestreamer-twitch-gui@0.6.1 postinstall C:\TWITCH\livestreamer-twitch-gui
> bower --config.interactive=false install

bower ENOGIT        git is not installed or not in the PATH

npm ERR! livestreamer-twitch-gui@0.6.1 postinstall: `bower --config.interactive=
false install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the livestreamer-twitch-gui@0.6.1 postinstall script.
npm ERR! This is most likely a problem with the livestreamer-twitch-gui package,

npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower --config.interactive=false install
npm ERR! You can get their info via:
npm ERR!     npm owner ls livestreamer-twitch-gui
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\TWITCH\livestreamer-twitch-gui
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\TWITCH\livestreamer-twitch-gui\npm-debug.log
npm ERR! not ok code 0

**Comment by brianpardee** [comment]
Nevermind. I got it working, though I didn't use the Node.js command prompt this time.
I right clicked on the repo in the GitHub app and selected Open in Git Shell, then ran the commands. I don't know if it matters or not, but before doing that I selected Git Bash as the default shell in the GitHub app's options.

**Comment by bastimeyer** [comment]
Hi, thanks for helping to test the master branch!

> bower ENOGIT git is not installed or not in the PATH

Git is a requirement for building the application (because of some dependencies of the npm + bower packages and because of [the metadata build task](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/20ac1337470553d72ff6b9249ef5e3bf2cb4e00b/build/tasks/custom/metadata.js#L69)).
Please make sure that the path of your git installation is properly set in your system's `PATH` variable. From the default windows shell and also from the "node.js command prompt" you can do this by typing `where git` or `echo %PATH%`...

I don't know the github app and also if it comes with a local git installation, but you should install the official "git for windows" from www.git-scm.com... The installer then adds git to the PATH variable, so you're able to use it from the default windows shell as well.

![image](https://cloud.githubusercontent.com/assets/467294/5794603/2effb6ba-9f76-11e4-903b-fe7c1e613e7c.png)

I'm glad you quickly managed to find a solution. :wink:
