### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by Arkhos02** [bastimeyer/livestreamer-twitch-gui#51]
Hello,
First thanks for this app im really loving it.
Can you consider implementing a night mode ? basically turning the background grey with white font.
Thanks

**Comment by bastimeyer** [comment]
Thanks!

Yes, this was already requested a couple of months ago and I also wanted to do this in the past, but there have always been tasks with a higher priority on my todo-list (missing features, etc). Adding multiple themes is actually one of the last things to be done, so right now this is not going to happen. The reason for this is also that there might be some design/layout changes in the future and having to deal with multiple themes is just more time consuming.

But if you want, you can always change the colors of the application and compile it by yourself.
See [/src/styles/config.less](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.7.1/src/styles/config.less)...
This actually might be a bit tricky and you will need to tinker around with it a bit since the stylesheets have evolved a bit over time and I don't know if changing the colors here will give you the perfect results on all parts/elements of the app.

**Comment by Arkhos02** [comment]
Hello,
Sure i know there is more important things to do , in fact i didnt know i could have done it myself , sorry to bother you with that.
i went ahead following your advices , it works great , thanks alot

**Comment by bastimeyer** [comment]
Cool, no problem...
I'll leave this thread open until there's support for theme switching

**Comment by bastimeyer** [comment]
I've just added support for multiple color themes and also added a dark theme.
Go to the settings menu, scroll down to the GUI section, select a different theme from the dropdown and apply your changes...

There are still some things that need to be changed, like different brand colors (button colors, etc) for different themes, but I think it's fine for a first iteration...
There's also a tiny delay between the time when the theme gets applied and when the window becomes visible after launching the application. I'm not sure if it's worth fixing it though...
