### ISSUE TITLE
Twitch chat pop-out

### ISSUE THREAD

**Issue by dragons4life** [bastimeyer/livestreamer-twitch-gui#60]
Can you make the twitch chat pop-up be a small window like this:
<img src='http://i.imgur.com/yK9VApv.png'/>
Instead of the huge one we get on a new tab?

**Comment by bastimeyer** [comment]
Sorry, this is not possible...
Someone already asked this a while ago https://github.com/bastimeyer/livestreamer-twitch-gui/issues/9#issuecomment-53150206

Detailed explanation:
I'm not opening the chat inside a new NW.js window, because I don't want the application to become a browser within a browser. This is not also a big security risk ([although it's possible to disable the nodejs/io.js context for new frames](https://github.com/nwjs/nw.js/wiki/Mini-browser-in-iframe)), but also not what the user expects when clicking links in chat, etc. The only solution to this right now is opening the chat [in the user's default browser](https://github.com/nwjs/nw.js/wiki/Shell#openexternaluri), but you're not able to control the look of the browser's window. You're basically just telling the OS to open a specific link in the default browser. What you probably mean is [this (window.open)](http://www.w3.org/TR/html5/browsers.html#apis-for-creating-and-navigating-browsing-contexts-by-name), but that's how you open new windows on a regular website. If you knew the user's default browser and the path to the executable, [you could to this](https://superuser.com/questions/459775/how-can-i-launch-a-browser-with-no-window-frame-or-tabs-address-bar), but this is *a little bit* out of scope.

**Comment by dragons4life** [comment]
Oh ok, thank you.
