### ISSUE TITLE
Application opens but it never comes out of minimize mode?

### ISSUE THREAD

**Issue by dragons4life** [bastimeyer/livestreamer-twitch-gui#62]
The program comes up and open up, it even shows on my taskbar and tray icon, but it won't open.

**Comment by killerpommes** [comment]
I had the same issue. i used "livestreamer-twitch-gui.exe --reset-window" to start it to fix the problem

**Comment by dragons4life** [comment]
Is that trough CMD?

Also I fix it by doing this, however this isn't the first time this happens.

Hover over the taskbar icon until the preview image window came up > right click > maximize

**Comment by killerpommes** [comment]
i used a windows Shortcut

**Comment by bastimeyer** [comment]
> i used "livestreamer-twitch-gui.exe --reset-window" to start it and fix the problem

Sounds like the window is being moved out of the visible desktop boundaries. If this happens again, could you please start the program with `--remote-debugging-port=8888` and then open `http://localhost:8888` in your browser? I'd like to know the width and height of your desktop and the value of
```js
JSON.parse(window.localStorage.getItem("app")).window.records[1]
```
Did you maximize the application window by any chance? I'm asking because I needed to implement a workaround for this: maximizing the window also triggers a `resize` event on the window in addition to the `maximize` event ([see here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.7.2/src/app/initializers/window.js#L94-L97)). So I'm curious if it's related to that or if there's something else which is causing this bug.


> [also is it normal to have 4 processes from this program?]

yes, NW.js (based on chromium) uses a [multi process architecture](https://www.chromium.org/developers/design-documents/multi-process-architecture)...

**Comment by dragons4life** [comment]
Yes, I noticed it happen when it was maximize, I had to delete the entire settings on the appdata folder to stop the bug, but I am pretty sure this happened when i maximize the window and leave it on the tray icon or minimize.

Hasn't happen to me as of now, but I am not using the full screen mode. (I'll try to reproduce the bug)

**Comment by killerpommes** [comment]
it seems to happen if you minimize the programm and than close it. (task manager or close via rightclick on taskbar) If i than try to start it, its started minimised.

**Comment by bastimeyer** [comment]
Thanks for reporting the issue guys!

This was related to NW.js and Windows: when minimizing the application window, NW.js fired a move event with the coordinates -32000,-32000. I also fixed the maximize event on OSX (fired multiple resize events during the animation).
Should be working on all platforms now and I guess I have to release another version, since this was *breaking* the application. :weary:

**Comment by dragons4life** [comment]
Can you add a hotkey (F5) to refresh the page your viewing? also is there a way to use "recent viewed/activity" without being sign in?

<s>didn't want to make another thread.</s>

**Comment by bastimeyer** [comment]
> F5

I'm not 100% sure, but I don't think you're able to add those keybindings in NW.js (same as mouse4+5 - back and forth)

> recent viewed/activity

Not yet implemented... Those are also just placeholders atm

**Comment by dragons4life** [comment]
It doesn't have to be "F5" but any key, you can even add "R".
