### ISSUE TITLE
Channel Pages finally here, but still no quality selection?

### ISSUE THREAD

**Issue by Anonanon** [bastimeyer/livestreamer-twitch-gui#63]
Sorry for bringing up a suggestion that was made in the past, but both #23 and #46 were closed.

I'm glad to see channel pages implemented in 7.2 but there is still no option to manually pick stream quality before loading it, preferably a right click menu. The channel pages already have all the established functions like chat pop out, follow, subscribe, copy url, ALL but quality selection. I just want to bring this suggestion back into the limelight and see what's up with this missing feature.

**Comment by bastimeyer** [comment]
Yes I know, it's being worked on and I did not forget (#23 is still open).
This feature wasn't included in `v0.7.2`, because it would have delayed the release even further and implementing this requires *a little bit* more work than adding a simple dropdown.
I also wanted the channel settings to at least have notification settings included before releasing another version. There are also VODs still to be implemented, which could then interfere with a settings menu at the bottom of the page (don't know yet).

I'm sorry that you still need to manually switch the quality for each stream you're watching, but I hope you understand my decision. Also, I'm working on this project in my free time, so I can't do much about it if things take some (more) time :confused:

**Comment by Anonanon** [comment]
No rush, the wait kind of passive so the delay into the next version is alright.

The reason why I would watch different channels in different qualities is because some channels use a very high bitrate so I would need to lower the quality. However some people stream at low bitrate due to mediocre internet and I would need to put it on Source otherwise it's just muddy garbage. Some channels also stream sprite based games and it looks like garbage on anything other than original resolution and quality.

**Comment by bastimeyer** [comment]
This was supposed to be closed by bcd269c, too.
