### ISSUE TITLE
login problems when using two clients with one account

### ISSUE THREAD

**Issue by kofi-annen** [bastimeyer/livestreamer-twitch-gui#65]
Hello! I love this app so much I feel I cannot use Twitch without it ever since I first discovered it on reddit a couple of months ago! yet I have to keep entering my password when I switch computers, which is a bit annoying. I'm using the gui with one account on two separate machines, one linux (32bit) another windows(64bit) - but I can only stay logged in on one of them as the other one logs out. I'm not sure if this is even a bug but I felt it is weird, I don't really understand code just a devout grateful user here.

Thanks in advance! and thanks for the development!

**Comment by bastimeyer** [comment]
Hi, thanks!
This issue has already been resolved in the release from a couple of days ago (`v0.7.2`). See #53, #47, #36...

Just go to the settings menu and enable `advanced settings`. On the login/logout menu you'll then be able to use the OAuth token login method. Copy the token of your logged-in device to your second one and use it instead of logging in with your password.

**Comment by kofi-annen** [comment]
I didn't know it was fixed but I did what you said and both seem to work now!

Thanks again, I'm so glad you are doing this project!

<3
