### ISSUE TITLE
[Feature] Snap to Edges

### ISSUE THREAD

**Issue by dragons4life** [bastimeyer/livestreamer-twitch-gui#68]

**Comment by bastimeyer** [comment]
?

Edge snapping is a feature a *good* window manager should be capable of. You're probably using Windows and I know that Windows is lacking those kind of features.
Implementing this is not only impossible with NW.js (we're just using web technologies here), but also generally a stupid idea: it's not the job of an application to rebuild a feature of a window manager.

Maybe you're just asking for sticky edges while moving the window, but also this is not the job an application. At least this *could* partially be implemented, but I don't see me doing this just for the sake of Windows. But I also wouldn't decline a good and working pull request for that.

**Comment by dragons4life** [comment]
What do you mean by window manager should have? only a few programs I have can snap to edges.
That being, PotPlayer/Rainmeter skins?

If you can't do it, or not worth the effort, is fine is not really a big feature I can't live without since most app I use don't have it.

**Comment by bastimeyer** [comment]
> What do you mean by window manager should have?

https://en.wikipedia.org/wiki/Window_manager
As I already said, it's the window manager's job to provide those features like edge snapping, tiling, etc. You mostly only see those features being implemented by programs on the application level that are windows exclusive, because the WM on Windows is just terrible. Those implementations are also very limited and don't work well together between multiple applications. Compare that with any WM on Linux or OSX.
