### ISSUE TITLE
Border for the main window

### ISSUE THREAD

**Issue by pingumania** [bastimeyer/livestreamer-twitch-gui#70]
Hi,

is it possible to add an border to the main window in a darker color than the background color?
Many windows have the same color as this gui and its sometimes hard to see where the window ends.

**Comment by bastimeyer** [comment]
Hi...
Isn't that the fault of your desktop theme for not adding a drop shadow to the window? I don't think that adding a colored border into the window itself is a good idea, since it doesn't fit the style of the application.

I've prepared a branch for you though ([window-border](https://github.com/bastimeyer/livestreamer-twitch-gui/compare/window-border)), so you can compile it and see for yourself.
`git clone -b window-border https://github.com/bastimeyer/livestreamer-twitch-gui`
The build instructions can be found [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.7.3/README.md#build) and [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.7.3/CONTRIBUTING.md#developing-and-building)

![image](https://cloud.githubusercontent.com/assets/467294/7053038/a23921fc-de32-11e4-9e34-baced9b05691.png)

**Comment by bastimeyer** [comment]
I'm closing this thread for now. This issue could be resolved by the implementation of multiple themes #51.
