### ISSUE TITLE
Streams do not close properly?

### ISSUE THREAD

**Issue by dragons4life** [bastimeyer/livestreamer-twitch-gui#74]
https://sendvid.com/sjp6suge

I tested this on 3 other players as well, is this a bug or is it meant to be like that?

Also stream type is HSL because if I choose HTTP, you can't switch streams without closing the player(s) first.

<i>Players: PotPlayer, Bakamplayer, Bomi, MPC-HC<i>

**Comment by bastimeyer** [comment]
Does your player run in a single instance for both streams?
A stream is considered open as long as its livestreamer process is running. So whenever you are launching another stream, the new livestreamer process will receive the same video player process ID of the old stream and will then override its input source. But since the first livestreamer process is still running, the GUI will tell you that the stream is still opened.

> Also stream type is HSL because if I choose HTTP, you can't switch streams without closing the player(s) first.

This should actually be the other way around. By choosing HLS as stream type, livestreamer will just pass through the HLS playlist to the player, so teminating the livestreamer process won't close the player then.

Also see this for player compatibility:
https://github.com/chrippa/livestreamer/blob/develop/docs/players.rst#player-compatibility

**Comment by dragons4life** [comment]
<blockquote>Does your player run in a single instance for both streams?</blockquote>
Yes, except for bakamplayer (but that's the only one were I don't have this problem since there is no option to run a single instance.) the others also have an option to run multiple instance, except MPC-HC (i think).

Bomi and Bakam are made from MPV.

<blockquote>This should actually be the other way around. By choosing HLS as stream type, livestreamer will just pass through the HLS playlist to the player, so teminating the livestreamer process won't close the player then.</blockquote>
I don't understand,  so HLS should be the one doing this not http?

I am not really bothered that much by this, I just tough it was a bug.

**Comment by bastimeyer** [comment]
> Yes, except for bakamplayer (but that's the only one were I don't have this problem

Then you should disable this for the other players as well to prevent this. Did you look for that single player instance problem on the livestreamer issue tracker?

> except MPC-HC (i think)

MPC-HC should have an option for this as well...

> I don't understand, so HLS should be the one doing this not http?

If I'm not mistaken, yes.

**Comment by dragons4life** [comment]
Also the biggest problem with using HLS, is that whenever the program recognizes the stream is "open" (when it's not), it won't open the stream.

like in the video I link, but thanks. I'll use HTTP.
