### ISSUE TITLE
Re: Stream quality override

### ISSUE THREAD

**Issue by Anonanon** [bastimeyer/livestreamer-twitch-gui#80]
Hi, it's me again. I've brought up a concern in past closed issues about choosing a stream quality on demand, because different channels and different games are best watched on different quality settings.

I see that in this latest 1.8.0 that feature has finally been implemented. However I feel that the way it was implemented is recreating the exact same problem as it was before.

Before:
1) click to go to You're Watching page
2) click Open Dialog
3) pick new desired quality

Now:
1) click channel name link
2) find/click very obscure, light gray wrench icon
3) assign a semi-permanent quality to that specific channel

There are two problems I see. First, I still have to jump through just as many hoops to be able to change quality. It's not really a solution if I still have to go through page after page to make a quality change. On top of that, the tiny grey wrench icon is extremely vague and does not explain anything to the user that very useful settings are hiding in there.

Secondly, this implementation just lets you override a quality setting for the channel. If a streamer decides on a whim to start playing a fast action 60 fps game and I desire to up my quality setting for it, this hidden stream override thing doesn't help. What I was expecting, the most optimal way in my opinion, is to click on a thumbnail and the quality dropbox immediately pops up. Maybe put a checkbox beside it "[x] Open chat" to knock down two problems with one stone.

Please see my rough mock up of what I'm trying to propose, I know it's ugly but it gets my point across:

![twitchgui](https://cloud.githubusercontent.com/assets/1048428/7364141/f828425a-ed50-11e4-86e0-2a5a9e4d2d8b.jpg)

**Comment by Poorchop** [comment]
I don't understand your before and after comparison. I'm using 0.8.0 and I can still go to You're watching > Open dialog and change the quality/open chat/close stream, etc. all from there. Clicking on the channel name and then the wrench icon just allows you to override your default stream quality settings. If you need to change to a higher quality stream on a whim, I don't understand why you're going into the individualized channel settings. Just go into the You're watching tab and change the quality from there. Either that or just close the stream and relaunch it so that the dialog box pops up, then change the quality from there.

Everything pretty much makes sense the way it is now. The only thing I agree on is that the wrench icon could be moved to a more visible area rather than the far top right.

**Comment by bastimeyer** [comment]
Hello again!
Yes, I do understand your complaint, but not all of your points are right.

First of all, you're always able to change the quality in the stream dialog, which can be accessed in many ways: by clicking the thumbnail in a stream list (again), by clicking the preview image on the featured channels page / channel page or by browsing the "watching" menu. So whenever a streamer is switching the game and you feel the need of changing the quality, then you can easily do it there.

The channel settings are saved permanently, so if there are streams that don't fit your global quality selection, you can make specific changes there.

A pre-stream-launch quality selection dialog only makes sense in those situations where you didn't start a stream yet, but you know for sure that you will need to change the quality afterwards. I think that this is a very, very rare case, since almost all users prefer a higher quality over a lower one.
The goal also always was to make it as simple as possible to launch streams (from your desktop, you're only always two clicks away from watching your favs: start the app, click the thumbnail). According to this, replacing the default dialog is out of the question, so this means that there needs to be another way of accessing the new dialog. Adding right-click actions to the GUI is something I don't want to do, because I think this would be confusing for most of the users. So what could be done is adding an icon/button to the stream thumbnails (featured streams / channel page previews). Let me see what I can do...

> The only thing I agree on is that the wrench icon could be moved to a more visible area rather than the far top right.

You both are probably right. The idea was to use the same style the stream lists were using, but I think this doesn't make sense for channel pages.

**Comment by Anonanon** [comment]
I'm about to invalidate my whole Issue.

I had no idea that what I drew in the mock up already exists when you click on the thumbnail when the stream is already playing. I don't know if I feel stupid or if the interface is hiding things from me. I used to think just clicking on the thumbnail again when a stream is already playing will just run a second instance of the video player.

Regardless, apologies and this can be closed. Perhaps it can be documented for dummies like me.
