### ISSUE TITLE
Some links under "Your" are unclickable

### ISSUE THREAD

**Issue by FISHunderscore** [bastimeyer/livestreamer-twitch-gui#83]
Hello,
I have a a problem where under the *Your* section of the GUI, only the *Favorites* link is clickable. *Subscriptions*, *Recent Activity*, and *Most Viewed* do not even change the cursor from a default arrow to a pointing finger. Clicking on them produces no action. Oddly, the *Favorites* tab is still clickable and works as it should, displaying my followed channels.

I don't know for sure, but I have a feeling that those sections haven't been added yet but have buttons already.

Aside from that, keep up the great work!

**Comment by bastimeyer** [comment]
Hello, thanks!

> I have a feeling that those sections haven't been added yet but have buttons already

That's right :stuck_out_tongue_winking_eye: 

I also don't know if I'm going to implement these menus. These were just early ideas and may be replaced in the future... Subscriptions can't be implemented because of missing API support and the other two require a different storage system to make them work like the way I want to.
