### ISSUE TITLE
Video players won't close (minor issue)

### ISSUE THREAD

**Issue by deetari** [bastimeyer/livestreamer-twitch-gui#86]
Bit of a strange issue (on Windows 8.1), but none of my media players (notably, VLC and MPC-HC) will close after I kill the stream from inside the GUI. The problem doesn't exist if I run Livestreamer from the command prompt, only from within the GUI.

I've tried running as admin as well as using older and newer versions of Livestreamer and the GUI, all to no avail. I've also tried changing the stream type and turning on and off the "do not close video player" option a few times. I feel like it worked in the past, but I admit I tend to just close the player window before returning to the GUI most of the time, so I could be wrong.

Didn't see anyone else with this issue, and it's hardly a major problem, but I figured I'd see if there was a known reason for this behavior.

**Comment by bastimeyer** [comment]
Hi,
I'm aware of this issue, but I don't know why this is happening.
This issue only exists on Windows and does not on Linux or OSX.

When clicking the close button in the stream popup, the GUI will send a [`SIGTERM`](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/8a40ec11caa8b7041cef41b72a3d7bf3143dc969/src/app/models/Livestreamer.js#L39) signal to the livestreamer child process in order to close the stream (and the video player). For some strange reason, livestreamer doesn't terminate the spawned player process, so the player window remains, but only on Windows. I've tried using the `SIGINT` signal, but this also didn't work. So I guess it's an issue of livestreamer.

**Comment by Frankthetankk** [comment]
I'm not sure if this is related or not. I've had the same problem, in windows, VLC would remain open after I killed the stream within the GUI. Which would leave a copy of VLC open as I closed or picked a new stream. The solution that worked for me is with VLC and not the GUI, in VLC, under Preferences , show ALL setting, then > Playlist > checkmark 'Play and exit'. Hope this helps.

**Comment by bastimeyer** [comment]
Thanks, @Frankthetankk! This does indeed work.
Maybe I should add an entry to this repo's wiki with player specific configs and fixes/workarounds...

**Comment by bastimeyer** [comment]
Added an entry to the wiki yesterday...
https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Player-configuration#player-configurations

**Comment by Frankthetankk** [comment]
Welcome, glad to help.
