### ISSUE TITLE
Favorite page auto refresh

### ISSUE THREAD

**Issue by Mangos02** [bastimeyer/livestreamer-twitch-gui#91]
it would be quite nice to make the favorites page auto refresh after like idk 5/10/30 + minuts. or auto refresh when reopening from the taskbar would also be a nice alternative. any comments on that?

**Comment by bastimeyer** [comment]
Hi...
I'm not a fan of automatically reloading content. Reloading the route when restoring the window from tray/taskbar sounds reasonable, though.

Btw: the followed streams are already being refreshed once every minute unless notifications are disabled. That's because of Ember's data bindings: it updates all stream stats (excluding preview images, which is intended) for all streams that stayed online during that time.

**Comment by bastimeyer** [comment]
Actually, the followed streams route should already be reloaded when restoring the window from tray/taskbar after clicking a notification. Totally forgot about that. See [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.8.0/src/app/controllers/NotificationController.js#L282) and [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.8.0/src/app/routes/ApplicationRoute.js#L23-L30).
This was broken on the master branch and is fixed now (c3a56a7).

**Comment by Mangos02** [comment]
if only i knew how to build a application, i tried doing the instruction on the main page but it doesnt work or i just dont know what im doing.
