### ISSUE TITLE
Error: Couldn't launch the stream

### ISSUE THREAD

**Issue by arthelinus** [bastimeyer/livestreamer-twitch-gui#99]
Was working before but i was getting InsecurePlatformWarning so i updated python to 2.7.10 and reinstalled livestreamer and now i get this error every time. Using the macx64 version
![screen shot 2015-05-27 at 01 29 57 1](https://cloud.githubusercontent.com/assets/6782462/7816275/9836a1b2-0410-11e5-989a-a975226ba7c7.png)

Launching livestreamer manually via terminal works.

**Comment by bastimeyer** [comment]
Hm, strange. I don't know why this is happening.
Seems like something is causing [this JS-Promise chain](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.9.0/src/app/controllers/LivestreamerController.js#L114-L141) to be rejected [without any error output](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.9.0/src/app/controllers/LivestreamerController.js#L207-L209). It could be [this method here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.9.0/src/app/controllers/LivestreamerController.js#L259-L301), since everything else should return an error message.

Would you please be so kind and debug the application for me and then see where this error is coming from? Just go through the chain step by step and see what is happening.
You can find all the necessary NW.js informations in [CONTRIBUTING.md](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.9.0/CONTRIBUTING.md#developing-and-building)

**Comment by Blackrame** [comment]
Hello. I can second that. Also using Mac64 version, also was getting the same error, also updated python and also having the same error now. 

I would like to debug the app for you, but I have no idea how to do it. I am very casual user.

**Comment by bastimeyer** [comment]
What is the output of `livestreamer --version --no-version-check` ?

**Comment by Blackrame** [comment]
It says: livestreamer 1.12.2

**Comment by arthelinus** [comment]
hmm, this is weird. I did the grunt dev and ran nw.js from build/tmp folder. But now when i run the nw.js for debugging, it runs smoothly without any problems. Same error in main application.
![screen shot 2015-05-27 at 07 04 43](https://cloud.githubusercontent.com/assets/6782462/7823436/d3fff56c-043e-11e5-9c0e-6360a6cf639e.png)

**Comment by bastimeyer** [comment]
Okay, that's weird... Thanks for taking the time finding a fix :+1: 

The main problem with OSX apps on Yosemite is, that you're unable to read the user's $PATH from within the application, so searching for livestreamer in all these paths is impossible. See the fix of #55: the solution was adding a fallback path (`/usr/local/bin/livestreamer`) hardcoded into the app. That's why it was working from the shell, because it was looking for livestreamer in a different location.

**Comment by Blackrame** [comment]
Sorry, so how will I make it work?

**Comment by arthelinus** [comment]
In the settings tab in the app just add this line, "/Library/Frameworks/Python.framework/Versions/2.7/bin/livestreamer" Change 2.7 with ur python version. use the command "which python" in terminal to find ur default version.
![screen shot 2015-05-27 at 08 48 10](https://cloud.githubusercontent.com/assets/6782462/7825216/82eb8786-044d-11e5-9d6e-b5683ba94289.png)

**Comment by Blackrame** [comment]
Thank you and thanks for this amazing app. Everything works now.

**Comment by bastimeyer** [comment]
I've added `/Library/Frameworks/Python.framework/Versions/Current/bin` to the livestreamer OSX fallback paths...

thanks, @Blackrame
